FROM golang:1.24.6-alpine

WORKDIR /app

# Install air, sqlc and migrate with postgresql support
RUN go install github.com/air-verse/air@latest && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest && \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Install necessary tools
RUN apk add --no-cache curl make git

# Create the appuser with a home directory and shell
RUN addgroup -g 1000 -S appgroup && \
    adduser -u 1000 -S appuser -G appgroup -s /bin/sh

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

# Set ownership
RUN chown -R appuser:appgroup .

# Change user
USER appuser

CMD ["air", "-c", ".air.toml"]
