FROM golang:1.24.6-alpine

WORKDIR /app

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Install necessary tools
RUN apk add --no-cache curl

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
