CREATE TYPE document_type   AS ENUM ('ID','PASSPORT','DRIVING_LICENSE','NATIONAL_ID','OTHER');
CREATE TYPE document_status AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE payment_method  AS ENUM ('CASH','MOBILE_MONEY','BANK_TRANSFER');
CREATE TYPE payment_status  AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE gender          AS ENUM ('MALE','FEMALE','OTHER');
CREATE TYPE marital_status  AS ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED');
CREATE TYPE religion        AS ENUM ('CHRISTIAN','MUSLIM','ATHEIST','HINDU','BUDDHIST','OTHER','NONE');
