// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: additional.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAdditional = `-- name: CreateAdditional :exec
INSERT INTO additional (
    resident_id, marital_status, religion, ethnicity, disability, education_level, languages_spoken
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateAdditionalParams struct {
	ResidentID      uuid.UUID `db:"resident_id" json:"resident_id"`
	MaritalStatus   *string   `db:"marital_status" json:"marital_status"`
	Religion        *string   `db:"religion" json:"religion"`
	Ethnicity       *string   `db:"ethnicity" json:"ethnicity"`
	Disability      *string   `db:"disability" json:"disability"`
	EducationLevel  *string   `db:"education_level" json:"education_level"`
	LanguagesSpoken []string  `db:"languages_spoken" json:"languages_spoken"`
}

func (q *Queries) CreateAdditional(ctx context.Context, arg CreateAdditionalParams) error {
	_, err := q.db.Exec(ctx, createAdditional,
		arg.ResidentID,
		arg.MaritalStatus,
		arg.Religion,
		arg.Ethnicity,
		arg.Disability,
		arg.EducationLevel,
		arg.LanguagesSpoken,
	)
	return err
}
