// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: address.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
    house_number, kebele_id, subcity_id, city_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, house_number, kebele_id, subcity_id, city_id, created_at, deleted_at
`

type CreateAddressParams struct {
	HouseNumber string    `db:"house_number" json:"house_number"`
	KebeleID    uuid.UUID `db:"kebele_id" json:"kebele_id"`
	SubcityID   uuid.UUID `db:"subcity_id" json:"subcity_id"`
	CityID      uuid.UUID `db:"city_id" json:"city_id"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.HouseNumber,
		arg.KebeleID,
		arg.SubcityID,
		arg.CityID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.HouseNumber,
		&i.KebeleID,
		&i.SubcityID,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
UPDATE address
SET deleted_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) DeleteAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT address.id, address.house_number, address.kebele_id, address.subcity_id, address.city_id, address.created_at, address.deleted_at, c.id, c.name, c.lat, c.lon, c.created_at, c.deleted_at, s.id, s.name, s.lat, s.lon, s.city_id, s.created_at, s.deleted_at, k.id, k.name, k.lat, k.lon, k.subcity_id, k.city_id, k.created_at, k.deleted_at
FROM address
JOIN city c ON address.city_id = c.id
JOIN subcity s ON address.subcity_id = s.id
JOIN kebele k ON address.kebele_id = k.id
WHERE address.id = $1 AND address.deleted_at IS NULL
`

type GetAddressRow struct {
	Address Address `db:"address" json:"address"`
	City    City    `db:"city" json:"city"`
	Subcity Subcity `db:"subcity" json:"subcity"`
	Kebele  Kebele  `db:"kebele" json:"kebele"`
}

func (q *Queries) GetAddress(ctx context.Context, id uuid.UUID) (GetAddressRow, error) {
	row := q.db.QueryRow(ctx, getAddress, id)
	var i GetAddressRow
	err := row.Scan(
		&i.Address.ID,
		&i.Address.HouseNumber,
		&i.Address.KebeleID,
		&i.Address.SubcityID,
		&i.Address.CityID,
		&i.Address.CreatedAt,
		&i.Address.DeletedAt,
		&i.City.ID,
		&i.City.Name,
		&i.City.Lat,
		&i.City.Lon,
		&i.City.CreatedAt,
		&i.City.DeletedAt,
		&i.Subcity.ID,
		&i.Subcity.Name,
		&i.Subcity.Lat,
		&i.Subcity.Lon,
		&i.Subcity.CityID,
		&i.Subcity.CreatedAt,
		&i.Subcity.DeletedAt,
		&i.Kebele.ID,
		&i.Kebele.Name,
		&i.Kebele.Lat,
		&i.Kebele.Lon,
		&i.Kebele.SubcityID,
		&i.Kebele.CityID,
		&i.Kebele.CreatedAt,
		&i.Kebele.DeletedAt,
	)
	return i, err
}

const getAddressByLocations = `-- name: GetAddressByLocations :one
SELECT id, house_number, kebele_id, subcity_id, city_id, created_at, deleted_at
FROM address
WHERE city_id = $1 AND 
    subcity_id = $2 AND 
    kebele_id = $3 AND 
    house_number = $4 AND 
    deleted_at IS NULL
`

type GetAddressByLocationsParams struct {
	CityID      uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID   uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID    uuid.UUID `db:"kebele_id" json:"kebele_id"`
	HouseNumber string    `db:"house_number" json:"house_number"`
}

func (q *Queries) GetAddressByLocations(ctx context.Context, arg GetAddressByLocationsParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByLocations,
		arg.CityID,
		arg.SubcityID,
		arg.KebeleID,
		arg.HouseNumber,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.HouseNumber,
		&i.KebeleID,
		&i.SubcityID,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRandomLocation = `-- name: GetRandomLocation :one
SELECT 
    c.id   AS city_id,
    s.id   AS subcity_id,
    k.id   AS kebele_id
FROM kebele k
JOIN subcity s ON k.subcity_id = s.id
JOIN city c ON s.city_id = c.id
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomLocationRow struct {
	CityID    uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID  uuid.UUID `db:"kebele_id" json:"kebele_id"`
}

func (q *Queries) GetRandomLocation(ctx context.Context) (GetRandomLocationRow, error) {
	row := q.db.QueryRow(ctx, getRandomLocation)
	var i GetRandomLocationRow
	err := row.Scan(&i.CityID, &i.SubcityID, &i.KebeleID)
	return i, err
}

const hardDeleteAddress = `-- name: HardDeleteAddress :exec
DELETE FROM address
WHERE id = $1
AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteAddress, id)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, house_number, kebele_id, subcity_id, city_id, created_at, deleted_at
FROM address
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListAddressesParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddresses, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.HouseNumber,
			&i.KebeleID,
			&i.SubcityID,
			&i.CityID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE address
SET
    house_number = COALESCE($1, house_number),
    kebele_id    = COALESCE($2, kebele_id),
    subcity_id   = COALESCE($3, subcity_id),
    city_id      = COALESCE($4, city_id)
WHERE id = $5
AND deleted_at IS NULL
RETURNING id, house_number, kebele_id, subcity_id, city_id, created_at, deleted_at
`

type UpdateAddressParams struct {
	HouseNumber *string    `db:"house_number" json:"house_number"`
	KebeleID    *uuid.UUID `db:"kebele_id" json:"kebele_id"`
	SubcityID   *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	CityID      *uuid.UUID `db:"city_id" json:"city_id"`
	ID          uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.HouseNumber,
		arg.KebeleID,
		arg.SubcityID,
		arg.CityID,
		arg.ID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.HouseNumber,
		&i.KebeleID,
		&i.SubcityID,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
