// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: address.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
  house_number, district, city_id
) VALUES ($1, $2, $3)
RETURNING id
`

type CreateAddressParams struct {
	HouseNumber string    `db:"house_number" json:"house_number"`
	District    string    `db:"district" json:"district"`
	CityID      uuid.UUID `db:"city_id" json:"city_id"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAddress, arg.HouseNumber, arg.District, arg.CityID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAddress = `-- name: GetAddress :one
SELECT id, house_number, district, city_id, created_at, deleted_at, search_vector FROM address
WHERE house_number = $1 AND district = $2 AND city_id = $3
LIMIT 1
`

type GetAddressParams struct {
	HouseNumber string    `db:"house_number" json:"house_number"`
	District    string    `db:"district" json:"district"`
	CityID      uuid.UUID `db:"city_id" json:"city_id"`
}

func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddress, arg.HouseNumber, arg.District, arg.CityID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.HouseNumber,
		&i.District,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
