// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgeGroupDistribution = `-- name: GetAgeGroupDistribution :many
SELECT
    age_group,
    COUNT(*) AS count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1) AS percentage
FROM resident_analytics
GROUP BY age_group
ORDER BY
    CASE age_group
        WHEN 'Under 18' THEN 1
        WHEN '18-24' THEN 2
        WHEN '25-34' THEN 3
        WHEN '35-44' THEN 4
        WHEN '45-54' THEN 5
        WHEN '55-64' THEN 6
        ELSE 7
    END
`

type GetAgeGroupDistributionRow struct {
	AgeGroup   string         `db:"age_group" json:"age_group"`
	Count      int64          `db:"count" json:"count"`
	Percentage pgtype.Numeric `db:"percentage" json:"percentage"`
}

func (q *Queries) GetAgeGroupDistribution(ctx context.Context) ([]GetAgeGroupDistributionRow, error) {
	rows, err := q.db.Query(ctx, getAgeGroupDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgeGroupDistributionRow{}
	for rows.Next() {
		var i GetAgeGroupDistributionRow
		if err := rows.Scan(&i.AgeGroup, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenderAgeGroupDistribution = `-- name: GetGenderAgeGroupDistribution :many
SELECT
    gender,
    age_group,
    COUNT(*) AS count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY gender), 1) AS percentage_within_gender
FROM resident_analytics
GROUP BY gender, age_group
ORDER BY gender,
    CASE age_group
        WHEN 'Under 18' THEN 1
        WHEN '18-24' THEN 2
        WHEN '25-34' THEN 3
        WHEN '35-44' THEN 4
        WHEN '45-54' THEN 5
        WHEN '55-64' THEN 6
        ELSE 7
    END
`

type GetGenderAgeGroupDistributionRow struct {
	Gender                 string         `db:"gender" json:"gender"`
	AgeGroup               string         `db:"age_group" json:"age_group"`
	Count                  int64          `db:"count" json:"count"`
	PercentageWithinGender pgtype.Numeric `db:"percentage_within_gender" json:"percentage_within_gender"`
}

func (q *Queries) GetGenderAgeGroupDistribution(ctx context.Context) ([]GetGenderAgeGroupDistributionRow, error) {
	rows, err := q.db.Query(ctx, getGenderAgeGroupDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGenderAgeGroupDistributionRow{}
	for rows.Next() {
		var i GetGenderAgeGroupDistributionRow
		if err := rows.Scan(
			&i.Gender,
			&i.AgeGroup,
			&i.Count,
			&i.PercentageWithinGender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenderDistribution = `-- name: GetGenderDistribution :many
SELECT
    gender,
    COUNT(*) AS count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1) AS percentage
FROM resident_analytics
GROUP BY gender
ORDER BY count DESC
`

type GetGenderDistributionRow struct {
	Gender     string         `db:"gender" json:"gender"`
	Count      int64          `db:"count" json:"count"`
	Percentage pgtype.Numeric `db:"percentage" json:"percentage"`
}

func (q *Queries) GetGenderDistribution(ctx context.Context) ([]GetGenderDistributionRow, error) {
	rows, err := q.db.Query(ctx, getGenderDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGenderDistributionRow{}
	for rows.Next() {
		var i GetGenderDistributionRow
		if err := rows.Scan(&i.Gender, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegistrationTrends = `-- name: GetRegistrationTrends :many
SELECT
    DATE_TRUNC('month', created_at) AS month,
    COUNT(*) AS new_residents
FROM resident_analytics
GROUP BY month
ORDER BY month
`

type GetRegistrationTrendsRow struct {
	Month        pgtype.Interval `db:"month" json:"month"`
	NewResidents int64           `db:"new_residents" json:"new_residents"`
}

func (q *Queries) GetRegistrationTrends(ctx context.Context) ([]GetRegistrationTrendsRow, error) {
	rows, err := q.db.Query(ctx, getRegistrationTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRegistrationTrendsRow{}
	for rows.Next() {
		var i GetRegistrationTrendsRow
		if err := rows.Scan(&i.Month, &i.NewResidents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
