// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListAuditLogs = `-- name: CountListAuditLogs :one
SELECT COUNT(*)
FROM audit_log log
JOIN "user" u ON u.id = log.actor_id
WHERE log.actor_id IS NOT NULL AND
    ($1::uuid IS NULL OR u.city_id = $1::uuid) AND
    ($2::uuid IS NULL OR u.subcity_id = $2::uuid) AND
    ($3::uuid IS NULL OR u.kebele_id = $3::uuid)
`

type CountListAuditLogsParams struct {
	CityID    *uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID  *uuid.UUID `db:"kebele_id" json:"kebele_id"`
}

func (q *Queries) CountListAuditLogs(ctx context.Context, arg CountListAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListAuditLogs, arg.CityID, arg.SubcityID, arg.KebeleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor_id, target_user_id, target_role_slug, action_type, object_type, object_id, diff_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID        uuid.UUID  `db:"actor_id" json:"actor_id"`
	TargetUserID   *uuid.UUID `db:"target_user_id" json:"target_user_id"`
	TargetRoleSlug *string    `db:"target_role_slug" json:"target_role_slug"`
	ActionType     string     `db:"action_type" json:"action_type"`
	ObjectType     string     `db:"object_type" json:"object_type"`
	ObjectID       *int64     `db:"object_id" json:"object_id"`
	DiffJson       []byte     `db:"diff_json" json:"diff_json"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.TargetUserID,
		arg.TargetRoleSlug,
		arg.ActionType,
		arg.ObjectType,
		arg.ObjectID,
		arg.DiffJson,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT log.id, log.actor_id, log.target_user_id, log.target_role_slug, log.action_type, log.object_type, log.object_id, log.diff_json, log.ts, ar.name AS actor_role,
    CONCAT_WS(' ', au.first_name, au.second_name, au.last_name) AS actor_name,
    CONCAT_WS(' ', tu.first_name, tu.second_name, tu.last_name) AS target_user_name
FROM audit_log log
JOIN "user" au ON au.id = log.actor_id
JOIN role ar ON ar.slug = au.role_slug
LEFT JOIN city c ON c.id = au.city_id
LEFT JOIN subcity sc ON sc.id = au.subcity_id
LEFT JOIN kebele k ON k.id = au.kebele_id
LEFT JOIN "user" tu ON tu.id = log.target_user_id
LEFT JOIN role r ON r.slug = log.target_role_slug
WHERE log.actor_id IS NOT NULL AND
    ($1::uuid IS NULL OR au.city_id = $1::uuid) AND
    ($2::uuid IS NULL OR au.subcity_id = $2::uuid) AND
    ($3::uuid IS NULL OR au.kebele_id = $3::uuid)
ORDER BY log.ts ASC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	CityID    *uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID  *uuid.UUID `db:"kebele_id" json:"kebele_id"`
	Offset    int32      `db:"offset" json:"offset"`
	Limit     int32      `db:"limit" json:"limit"`
}

type ListAuditLogsRow struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	ActorID        uuid.UUID  `db:"actor_id" json:"actor_id"`
	TargetUserID   *uuid.UUID `db:"target_user_id" json:"target_user_id"`
	TargetRoleSlug *string    `db:"target_role_slug" json:"target_role_slug"`
	ActionType     string     `db:"action_type" json:"action_type"`
	ObjectType     string     `db:"object_type" json:"object_type"`
	ObjectID       *int64     `db:"object_id" json:"object_id"`
	DiffJson       []byte     `db:"diff_json" json:"diff_json"`
	Ts             time.Time  `db:"ts" json:"ts"`
	ActorRole      string     `db:"actor_role" json:"actor_role"`
	ActorName      string     `db:"actor_name" json:"actor_name"`
	TargetUserName string     `db:"target_user_name" json:"target_user_name"`
}

// Returns audit logs under scope
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.CityID,
		arg.SubcityID,
		arg.KebeleID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.TargetUserID,
			&i.TargetRoleSlug,
			&i.ActionType,
			&i.ObjectType,
			&i.ObjectID,
			&i.DiffJson,
			&i.Ts,
			&i.ActorRole,
			&i.ActorName,
			&i.TargetUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAuditLogs = `-- name: ListUserAuditLogs :many
SELECT log.id, log.actor_id, log.target_user_id, log.target_role_slug, log.action_type, log.object_type, log.object_id, log.diff_json, log.ts, CONCAT_WS(' ', au.first_name, au.second_name, au.last_name) AS actor_name
FROM audit_log log
JOIN "user" au ON au.id = log.actor_id
LEFT JOIN city c ON c.id = au.city_id
LEFT JOIN subcity sc ON sc.id = au.subcity_id
LEFT JOIN kebele k ON k.id = au.kebele_id
LEFT JOIN "user" tu ON tu.id = log.target_user_id
LEFT JOIN role r ON r.slug = log.target_role_slug
WHERE log.target_user_id IS NOT NULL AND
    ($1::uuid IS NULL OR au.city_id = $1::uuid) AND
    ($2::uuid IS NULL OR au.subcity_id = $2::uuid) AND
    ($3::uuid IS NULL OR au.kebele_id = $3::uuid)
ORDER BY log.ts ASC
LIMIT $5 OFFSET $4
`

type ListUserAuditLogsParams struct {
	CityID    *uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID  *uuid.UUID `db:"kebele_id" json:"kebele_id"`
	Offset    int32      `db:"offset" json:"offset"`
	Limit     int32      `db:"limit" json:"limit"`
}

type ListUserAuditLogsRow struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	ActorID        uuid.UUID  `db:"actor_id" json:"actor_id"`
	TargetUserID   *uuid.UUID `db:"target_user_id" json:"target_user_id"`
	TargetRoleSlug *string    `db:"target_role_slug" json:"target_role_slug"`
	ActionType     string     `db:"action_type" json:"action_type"`
	ObjectType     string     `db:"object_type" json:"object_type"`
	ObjectID       *int64     `db:"object_id" json:"object_id"`
	DiffJson       []byte     `db:"diff_json" json:"diff_json"`
	Ts             time.Time  `db:"ts" json:"ts"`
	ActorName      string     `db:"actor_name" json:"actor_name"`
}

// Returns user related audit logs
func (q *Queries) ListUserAuditLogs(ctx context.Context, arg ListUserAuditLogsParams) ([]ListUserAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listUserAuditLogs,
		arg.CityID,
		arg.SubcityID,
		arg.KebeleID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAuditLogsRow{}
	for rows.Next() {
		var i ListUserAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.TargetUserID,
			&i.TargetRoleSlug,
			&i.ActionType,
			&i.ObjectType,
			&i.ObjectID,
			&i.DiffJson,
			&i.Ts,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
