// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const canActorGrantPermissionToRole = `-- name: CanActorGrantPermissionToRole :one
SELECT CASE
      WHEN (
          -- 1. actor role is strictly higher than target role
          (SELECT level_rank FROM role WHERE slug = (
              SELECT role_slug FROM "user" u WHERE u.id = $1
          )) <
          (SELECT level_rank FROM role r WHERE r.slug = $2)
      ) AND (
          -- 2. permission exists in role(s) at or below actor’s level
          EXISTS (
              SELECT 1
              FROM role_permission rp
              JOIN role r ON r.slug = rp.role_slug
              WHERE rp.permission_name = $3
                AND r.level_rank >= (
                    SELECT level_rank FROM role WHERE slug = (
                        SELECT role_slug FROM "user" WHERE id = $1
                    )
                )
          )
      )
      THEN true
      ELSE false
  END AS ok
`

type CanActorGrantPermissionToRoleParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Role       string    `db:"role" json:"role"`
	Permission string    `db:"permission" json:"permission"`
}

func (q *Queries) CanActorGrantPermissionToRole(ctx context.Context, arg CanActorGrantPermissionToRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, canActorGrantPermissionToRole, arg.ID, arg.Role, arg.Permission)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const canActorManipulateRole = `-- name: CanActorManipulateRole :one
SELECT CASE
    WHEN actor.level_rank = target.level_rank THEN false   -- same role
    WHEN actor.level_rank < target.level_rank THEN true
    ELSE false
END AS ok
FROM role AS actor, role AS target
WHERE actor.slug = (SELECT role_slug FROM "user" WHERE id = $1)
  AND target.slug = $2
`

type CanActorManipulateRoleParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Role string    `db:"role" json:"role"`
}

// returns true if the actor’s role is strictly more powerful than target_role
func (q *Queries) CanActorManipulateRole(ctx context.Context, arg CanActorManipulateRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, canActorManipulateRole, arg.ID, arg.Role)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const canActorTouchTarget = `-- name: CanActorTouchTarget :one
SELECT CASE
    WHEN $1 = $2 THEN false
    WHEN a.role_slug = t.role_slug THEN false
    WHEN (SELECT level_rank FROM role WHERE slug = a.role_slug)
         >= (SELECT level_rank FROM role WHERE slug = t.role_slug) THEN false
    WHEN (a.city_id     IS NOT NULL AND a.city_id     = t.city_id) OR
         (a.subcity_id IS NOT NULL AND a.subcity_id = t.subcity_id) OR
         (a.kebele_id IS NOT NULL AND a.kebele_id = t.kebele_id) THEN true
    ELSE false
END AS ok
FROM "user" a, "user" t
WHERE a.id = $1 AND t.id = $2
`

type CanActorTouchTargetParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Column2 interface{} `db:"column_2" json:"column_2"`
}

func (q *Queries) CanActorTouchTarget(ctx context.Context, arg CanActorTouchTargetParams) (bool, error) {
	row := q.db.QueryRow(ctx, canActorTouchTarget, arg.Column1, arg.Column2)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
