// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: biometric.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createBiometric = `-- name: CreateBiometric :exec
INSERT INTO biometric (
  resident_id, fingerprint, blood_type, face
) VALUES ($1, $2, $3, $4)
`

type CreateBiometricParams struct {
	ResidentID  uuid.UUID `db:"resident_id" json:"resident_id"`
	Fingerprint []byte    `db:"fingerprint" json:"fingerprint"`
	BloodType   string    `db:"blood_type" json:"blood_type"`
	Face        string    `db:"face" json:"face"`
}

func (q *Queries) CreateBiometric(ctx context.Context, arg CreateBiometricParams) error {
	_, err := q.db.Exec(ctx, createBiometric,
		arg.ResidentID,
		arg.Fingerprint,
		arg.BloodType,
		arg.Face,
	)
	return err
}
