// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: biometric.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createBiometric = `-- name: CreateBiometric :one
INSERT INTO biometric (resident_id, face_url, blood_type)
VALUES ($1, $2, $3)
RETURNING id, resident_id, fingerprint, blood_type, face_url, created_at, deleted_at
`

type CreateBiometricParams struct {
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	FaceUrl    string    `db:"face_url" json:"face_url"`
	BloodType  string    `db:"blood_type" json:"blood_type"`
}

func (q *Queries) CreateBiometric(ctx context.Context, arg CreateBiometricParams) (Biometric, error) {
	row := q.db.QueryRow(ctx, createBiometric, arg.ResidentID, arg.FaceUrl, arg.BloodType)
	var i Biometric
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Fingerprint,
		&i.BloodType,
		&i.FaceUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBiometric = `-- name: GetBiometric :one
SELECT id, resident_id, fingerprint, blood_type, face_url, created_at, deleted_at FROM biometric WHERE resident_id = $1
`

func (q *Queries) GetBiometric(ctx context.Context, residentID uuid.UUID) (Biometric, error) {
	row := q.db.QueryRow(ctx, getBiometric, residentID)
	var i Biometric
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Fingerprint,
		&i.BloodType,
		&i.FaceUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBiometric = `-- name: UpdateBiometric :one
UPDATE biometric
SET
    face_url = COALESCE($2, face_url),
    blood_type = COALESCE($3, blood_type)
WHERE resident_id = $1
RETURNING id, resident_id, fingerprint, blood_type, face_url, created_at, deleted_at
`

type UpdateBiometricParams struct {
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	FaceUrl    *string   `db:"face_url" json:"face_url"`
	BloodType  *string   `db:"blood_type" json:"blood_type"`
}

func (q *Queries) UpdateBiometric(ctx context.Context, arg UpdateBiometricParams) (Biometric, error) {
	row := q.db.QueryRow(ctx, updateBiometric, arg.ResidentID, arg.FaceUrl, arg.BloodType)
	var i Biometric
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Fingerprint,
		&i.BloodType,
		&i.FaceUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
