// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: city.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCity = `-- name: CreateCity :one
INSERT INTO city (name)
VALUES ($1)
RETURNING id, name, admin_id, search_vector, created_at, deleted_at
`

func (q *Queries) CreateCity(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRow(ctx, createCity, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.SearchVector,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCity = `-- name: GetCity :one
SELECT c.id, c.name, c.admin_id, c.search_vector, c.created_at, c.deleted_at,
a.first_name,
a.second_name,
a.last_name
FROM city c
LEFT JOIN actor a ON a.id = c.admin_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCityRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	AdminID      *uuid.UUID `db:"admin_id" json:"admin_id"`
	SearchVector *string    `db:"search_vector" json:"search_vector"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
	FirstName    *string    `db:"first_name" json:"first_name"`
	SecondName   *string    `db:"second_name" json:"second_name"`
	LastName     *string    `db:"last_name" json:"last_name"`
}

func (q *Queries) GetCity(ctx context.Context, id uuid.UUID) (GetCityRow, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i GetCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.SearchVector,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.SecondName,
		&i.LastName,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT c.id, c.name, c.admin_id, c.search_vector, c.created_at, c.deleted_at,
a.first_name,
a.second_name,
a.last_name,
COUNT(*) OVER() as count
FROM city c
LEFT JOIN actor a ON a.id = c.admin_id
WHERE c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCitiesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCitiesRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	AdminID      *uuid.UUID `db:"admin_id" json:"admin_id"`
	SearchVector *string    `db:"search_vector" json:"search_vector"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
	FirstName    *string    `db:"first_name" json:"first_name"`
	SecondName   *string    `db:"second_name" json:"second_name"`
	LastName     *string    `db:"last_name" json:"last_name"`
	Count        int64      `db:"count" json:"count"`
}

func (q *Queries) ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesRow{}
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdminID,
			&i.SearchVector,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
