// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: city.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListCities = `-- name: CountListCities :one
SELECT COUNT(*)
FROM city
WHERE deleted_at IS NULL
`

func (q *Queries) CountListCities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListCities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO city (name)
VALUES ($1)
RETURNING id, name, created_at, deleted_at
`

func (q *Queries) CreateCity(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRow(ctx, createCity, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCity = `-- name: GetCity :one
SELECT c.id, c.name, c.created_at, c.deleted_at, u.id as admin_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS admin_name
FROM city c
LEFT JOIN "user" u ON u.city_id = c.id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCityRow struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
	AdminID   *uuid.UUID `db:"admin_id" json:"admin_id"`
	AdminName string     `db:"admin_name" json:"admin_name"`
}

func (q *Queries) GetCity(ctx context.Context, id uuid.UUID) (GetCityRow, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i GetCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.AdminID,
		&i.AdminName,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT c.id, c.name, c.created_at, c.deleted_at, u.id as admin_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS admin_name
FROM city c
LEFT JOIN "user" u ON u.city_id = c.id
WHERE c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCitiesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCitiesRow struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
	AdminID   *uuid.UUID `db:"admin_id" json:"admin_id"`
	AdminName string     `db:"admin_name" json:"admin_name"`
}

func (q *Queries) ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesRow{}
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.AdminID,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
