// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: city.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCity = `-- name: CreateCity :one
INSERT INTO city (name)
VALUES ($1)
RETURNING id, name, admin_id, created_at, deleted_at, search_vector
`

func (q *Queries) CreateCity(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRow(ctx, createCity, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const createKebele = `-- name: CreateKebele :one
INSERT INTO kebele (name, city_id)
VALUES ($1, $2)
RETURNING id, name, subcity_id, executive_id, city_id, created_at, deleted_at, search_vector
`

type CreateKebeleParams struct {
	Name   string    `db:"name" json:"name"`
	CityID uuid.UUID `db:"city_id" json:"city_id"`
}

func (q *Queries) CreateKebele(ctx context.Context, arg CreateKebeleParams) (Kebele, error) {
	row := q.db.QueryRow(ctx, createKebele, arg.Name, arg.CityID)
	var i Kebele
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubcityID,
		&i.ExecutiveID,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getCity = `-- name: GetCity :one
SELECT c.id, c.name, c.admin_id, c.created_at, c.deleted_at, c.search_vector,
a.first_name,
a.second_name,
a.last_name
FROM city c
LEFT JOIN actor a ON a.id = c.admin_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCityRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	AdminID      *uuid.UUID `db:"admin_id" json:"admin_id"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
	SearchVector *string    `db:"search_vector" json:"search_vector"`
	FirstName    *string    `db:"first_name" json:"first_name"`
	SecondName   *string    `db:"second_name" json:"second_name"`
	LastName     *string    `db:"last_name" json:"last_name"`
}

func (q *Queries) GetCity(ctx context.Context, id uuid.UUID) (GetCityRow, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i GetCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.FirstName,
		&i.SecondName,
		&i.LastName,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT c.id, c.name, c.admin_id, c.created_at, c.deleted_at, c.search_vector,
a.first_name,
a.second_name,
a.last_name
FROM city c
LEFT JOIN actor a ON a.id = c.admin_id
WHERE c.deleted_at IS NULL
ORDER BY c.name ASC
`

type ListCitiesRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	AdminID      *uuid.UUID `db:"admin_id" json:"admin_id"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
	SearchVector *string    `db:"search_vector" json:"search_vector"`
	FirstName    *string    `db:"first_name" json:"first_name"`
	SecondName   *string    `db:"second_name" json:"second_name"`
	LastName     *string    `db:"last_name" json:"last_name"`
}

func (q *Queries) ListCities(ctx context.Context) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesRow{}
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdminID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.SearchVector,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
