// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: core.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCity = `-- name: CreateCity :one
INSERT INTO city (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, admin_id, created_at, deleted_at, search_vector
`

type CreateCityParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity, arg.ID, arg.Name, arg.CreatedAt)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const createKebele = `-- name: CreateKebele :one
INSERT INTO kebele (id, name, city_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, subcity_id, executive_id, city_id, created_at, deleted_at, search_vector
`

type CreateKebeleParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CityID    uuid.UUID `db:"city_id" json:"city_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateKebele(ctx context.Context, arg CreateKebeleParams) (Kebele, error) {
	row := q.db.QueryRow(ctx, createKebele,
		arg.ID,
		arg.Name,
		arg.CityID,
		arg.CreatedAt,
	)
	var i Kebele
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubcityID,
		&i.ExecutiveID,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
