// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: core.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCity = `-- name: CreateCity :one
INSERT INTO city (id, name, region_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, region_id, created_at, deleted_at, search_vector
`

type CreateCityParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	RegionID  uuid.UUID `db:"region_id" json:"region_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity,
		arg.ID,
		arg.Name,
		arg.RegionID,
		arg.CreatedAt,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const createRegion = `-- name: CreateRegion :one
INSERT INTO region (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, created_at, deleted_at, search_vector
`

type CreateRegionParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, createRegion, arg.ID, arg.Name, arg.CreatedAt)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
