// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: document.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :exec
INSERT INTO document (
  type, number, resident_id, url, status
) VALUES ($1, $2, $3, $4, $5)
`

type CreateDocumentParams struct {
	Type       string    `db:"type" json:"type"`
	Number     string    `db:"number" json:"number"`
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	Url        string    `db:"url" json:"url"`
	Status     string    `db:"status" json:"status"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.Type,
		arg.Number,
		arg.ResidentID,
		arg.Url,
		arg.Status,
	)
	return err
}
