// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: document.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO document (
    resident_id, url, status
) VALUES (
    $1, $2, $3
)
RETURNING id, resident_id, url, status, created_at, deleted_at
`

type CreateDocumentParams struct {
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	Url        string    `db:"url" json:"url"`
	Status     string    `db:"status" json:"status"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.ResidentID, arg.Url, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
UPDATE document
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, resident_id, url, status, created_at, deleted_at
FROM document
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByResident = `-- name: GetDocumentByResident :one
SELECT id, resident_id, url, status, created_at, deleted_at
FROM document
WHERE resident_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByResident(ctx context.Context, residentID uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByResident, residentID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResidentDocuments = `-- name: GetResidentDocuments :many
SELECT id, resident_id, url, status, created_at, deleted_at
FROM document
WHERE resident_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetResidentDocuments(ctx context.Context, residentID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getResidentDocuments, residentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ResidentID,
			&i.Url,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteDocument = `-- name: HardDeleteDocument :exec
DELETE FROM document
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteDocument, id)
	return err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, resident_id, url, status, created_at, deleted_at
FROM document
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListDocumentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ResidentID,
			&i.Url,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE document
SET
    url    = COALESCE($1, url),
    status = COALESCE($2, status)
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, resident_id, url, status, created_at, deleted_at
`

type UpdateDocumentParams struct {
	Url    *string   `db:"url" json:"url"`
	Status *string   `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument, arg.Url, arg.Status, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
