// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emergency.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEmergency = `-- name: CreateEmergency :exec
INSERT INTO emergency (
  resident_id, name, relation, phone
) VALUES ($1, $2, $3, $4)
`

type CreateEmergencyParams struct {
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	Name       string    `db:"name" json:"name"`
	Relation   string    `db:"relation" json:"relation"`
	Phone      string    `db:"phone" json:"phone"`
}

func (q *Queries) CreateEmergency(ctx context.Context, arg CreateEmergencyParams) error {
	_, err := q.db.Exec(ctx, createEmergency,
		arg.ResidentID,
		arg.Name,
		arg.Relation,
		arg.Phone,
	)
	return err
}
