// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emergency.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEmergencyContact = `-- name: CreateEmergencyContact :one
INSERT INTO emergency (
    resident_id, name, relation, phone, email
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, resident_id, name, relation, phone, email, created_at, deleted_at
`

type CreateEmergencyContactParams struct {
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	Name       string    `db:"name" json:"name"`
	Relation   string    `db:"relation" json:"relation"`
	Phone      string    `db:"phone" json:"phone"`
	Email      *string   `db:"email" json:"email"`
}

func (q *Queries) CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) (Emergency, error) {
	row := q.db.QueryRow(ctx, createEmergencyContact,
		arg.ResidentID,
		arg.Name,
		arg.Relation,
		arg.Phone,
		arg.Email,
	)
	var i Emergency
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Name,
		&i.Relation,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmergencyContact = `-- name: DeleteEmergencyContact :exec
UPDATE emergency
SET deleted_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) DeleteEmergencyContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmergencyContact, id)
	return err
}

const getEmergencyContact = `-- name: GetEmergencyContact :one
SELECT id, resident_id, name, relation, phone, email, created_at, deleted_at
FROM emergency
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetEmergencyContact(ctx context.Context, id uuid.UUID) (Emergency, error) {
	row := q.db.QueryRow(ctx, getEmergencyContact, id)
	var i Emergency
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Name,
		&i.Relation,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmergencyContactByResident = `-- name: GetEmergencyContactByResident :one
SELECT id, resident_id, name, relation, phone, email, created_at, deleted_at
FROM emergency
WHERE resident_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetEmergencyContactByResident(ctx context.Context, residentID uuid.UUID) (Emergency, error) {
	row := q.db.QueryRow(ctx, getEmergencyContactByResident, residentID)
	var i Emergency
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Name,
		&i.Relation,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteEmergencyContact = `-- name: HardDeleteEmergencyContact :exec
DELETE FROM emergency
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteEmergencyContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEmergencyContact, id)
	return err
}

const listEmergencyContacts = `-- name: ListEmergencyContacts :many
SELECT id, resident_id, name, relation, phone, email, created_at, deleted_at
FROM emergency
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListEmergencyContactsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListEmergencyContacts(ctx context.Context, arg ListEmergencyContactsParams) ([]Emergency, error) {
	rows, err := q.db.Query(ctx, listEmergencyContacts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Emergency{}
	for rows.Next() {
		var i Emergency
		if err := rows.Scan(
			&i.ID,
			&i.ResidentID,
			&i.Name,
			&i.Relation,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmergencyContact = `-- name: UpdateEmergencyContact :one
UPDATE emergency
SET
    name     = COALESCE($1, name),
    relation = COALESCE($2, relation),
    phone    = COALESCE($3, phone),
    email    = COALESCE($4, email)
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, resident_id, name, relation, phone, email, created_at, deleted_at
`

type UpdateEmergencyContactParams struct {
	Name     *string   `db:"name" json:"name"`
	Relation *string   `db:"relation" json:"relation"`
	Phone    *string   `db:"phone" json:"phone"`
	Email    *string   `db:"email" json:"email"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) (Emergency, error) {
	row := q.db.QueryRow(ctx, updateEmergencyContact,
		arg.Name,
		arg.Relation,
		arg.Phone,
		arg.Email,
		arg.ID,
	)
	var i Emergency
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Name,
		&i.Relation,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
