// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: employment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEmployment = `-- name: CreateEmployment :exec
INSERT INTO employment (
  resident_id, status, occupation, employer_name, work_address
) VALUES ($1, $2, $3, $4, $5)
`

type CreateEmploymentParams struct {
	ResidentID   uuid.UUID `db:"resident_id" json:"resident_id"`
	Status       string    `db:"status" json:"status"`
	Occupation   *string   `db:"occupation" json:"occupation"`
	EmployerName *string   `db:"employer_name" json:"employer_name"`
	WorkAddress  *string   `db:"work_address" json:"work_address"`
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) error {
	_, err := q.db.Exec(ctx, createEmployment,
		arg.ResidentID,
		arg.Status,
		arg.Occupation,
		arg.EmployerName,
		arg.WorkAddress,
	)
	return err
}
