// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: employment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEmployment = `-- name: CreateEmployment :one
INSERT INTO employment (
    resident_id, status, type, occupation, employer_name, work_address
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, resident_id, status, type, occupation, employer_name, work_address, created_at, deleted_at
`

type CreateEmploymentParams struct {
	ResidentID   uuid.UUID `db:"resident_id" json:"resident_id"`
	Status       string    `db:"status" json:"status"`
	Type         *string   `db:"type" json:"type"`
	Occupation   *string   `db:"occupation" json:"occupation"`
	EmployerName *string   `db:"employer_name" json:"employer_name"`
	WorkAddress  *string   `db:"work_address" json:"work_address"`
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) (Employment, error) {
	row := q.db.QueryRow(ctx, createEmployment,
		arg.ResidentID,
		arg.Status,
		arg.Type,
		arg.Occupation,
		arg.EmployerName,
		arg.WorkAddress,
	)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Status,
		&i.Type,
		&i.Occupation,
		&i.EmployerName,
		&i.WorkAddress,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmployment = `-- name: DeleteEmployment :exec
UPDATE employment
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteEmployment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployment, id)
	return err
}

const getEmployment = `-- name: GetEmployment :one
SELECT id, resident_id, status, type, occupation, employer_name, work_address, created_at, deleted_at
FROM employment
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEmployment(ctx context.Context, id uuid.UUID) (Employment, error) {
	row := q.db.QueryRow(ctx, getEmployment, id)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Status,
		&i.Type,
		&i.Occupation,
		&i.EmployerName,
		&i.WorkAddress,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmploymentByResident = `-- name: GetEmploymentByResident :one
SELECT id, resident_id, status, type, occupation, employer_name, work_address, created_at, deleted_at
FROM employment
WHERE resident_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEmploymentByResident(ctx context.Context, residentID uuid.UUID) (Employment, error) {
	row := q.db.QueryRow(ctx, getEmploymentByResident, residentID)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Status,
		&i.Type,
		&i.Occupation,
		&i.EmployerName,
		&i.WorkAddress,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteEmployment = `-- name: HardDeleteEmployment :exec
DELETE FROM employment
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteEmployment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEmployment, id)
	return err
}

const listEmployments = `-- name: ListEmployments :many
SELECT id, resident_id, status, type, occupation, employer_name, work_address, created_at, deleted_at
FROM employment
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListEmploymentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListEmployments(ctx context.Context, arg ListEmploymentsParams) ([]Employment, error) {
	rows, err := q.db.Query(ctx, listEmployments, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employment{}
	for rows.Next() {
		var i Employment
		if err := rows.Scan(
			&i.ID,
			&i.ResidentID,
			&i.Status,
			&i.Type,
			&i.Occupation,
			&i.EmployerName,
			&i.WorkAddress,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployment = `-- name: UpdateEmployment :one
UPDATE employment
SET
    status        = COALESCE($1, status),
    type          = COALESCE($2, type),
    occupation    = COALESCE($3, occupation),
    employer_name = COALESCE($4, employer_name),
    work_address  = COALESCE($5, work_address)
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, resident_id, status, type, occupation, employer_name, work_address, created_at, deleted_at
`

type UpdateEmploymentParams struct {
	Status       *string   `db:"status" json:"status"`
	Type         *string   `db:"type" json:"type"`
	Occupation   *string   `db:"occupation" json:"occupation"`
	EmployerName *string   `db:"employer_name" json:"employer_name"`
	WorkAddress  *string   `db:"work_address" json:"work_address"`
	ID           uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateEmployment(ctx context.Context, arg UpdateEmploymentParams) (Employment, error) {
	row := q.db.QueryRow(ctx, updateEmployment,
		arg.Status,
		arg.Type,
		arg.Occupation,
		arg.EmployerName,
		arg.WorkAddress,
		arg.ID,
	)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Status,
		&i.Type,
		&i.Occupation,
		&i.EmployerName,
		&i.WorkAddress,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
