// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_all.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAllResidents = `-- name: GetAllResidents :many
SELECT
  id,
  email,
  first_name,
  second_name,
  last_name,
  birth_date,
  gender,
  phone,
  marital_status,
  religion,
  ethnicity,
  disability_status,
  education_level,
  languages_spoken,
  address_id,
  created_at,
  deleted_at
FROM resident
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type GetAllResidentsRow struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	Email            string     `db:"email" json:"email"`
	FirstName        string     `db:"first_name" json:"first_name"`
	SecondName       string     `db:"second_name" json:"second_name"`
	LastName         string     `db:"last_name" json:"last_name"`
	BirthDate        time.Time  `db:"birth_date" json:"birth_date"`
	Gender           string     `db:"gender" json:"gender"`
	Phone            string     `db:"phone" json:"phone"`
	MaritalStatus    string     `db:"marital_status" json:"marital_status"`
	Religion         string     `db:"religion" json:"religion"`
	Ethnicity        *string    `db:"ethnicity" json:"ethnicity"`
	DisabilityStatus *string    `db:"disability_status" json:"disability_status"`
	EducationLevel   *string    `db:"education_level" json:"education_level"`
	LanguagesSpoken  string     `db:"languages_spoken" json:"languages_spoken"`
	AddressID        *uuid.UUID `db:"address_id" json:"address_id"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
	DeletedAt        *time.Time `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) GetAllResidents(ctx context.Context) ([]GetAllResidentsRow, error) {
	rows, err := q.db.Query(ctx, getAllResidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllResidentsRow{}
	for rows.Next() {
		var i GetAllResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.MaritalStatus,
			&i.Religion,
			&i.Ethnicity,
			&i.DisabilityStatus,
			&i.EducationLevel,
			&i.LanguagesSpoken,
			&i.AddressID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
