// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_all.sql

package repository

import (
	"context"
)

const getAllResidents = `-- name: GetAllResidents :many
SELECT id, email, first_name, second_name, last_name, birth_date, gender, phone, marital_status, religion, ethnicity, disability_status, education_level, languages_spoken, address_id, created_at, deleted_at, search_vector
FROM resident
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllResidents(ctx context.Context) ([]Resident, error) {
	rows, err := q.db.Query(ctx, getAllResidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resident{}
	for rows.Next() {
		var i Resident
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.MaritalStatus,
			&i.Religion,
			&i.Ethnicity,
			&i.DisabilityStatus,
			&i.EducationLevel,
			&i.LanguagesSpoken,
			&i.AddressID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
