// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_resident.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getResidentFull = `-- name: GetResidentFull :one
SELECT
  r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.marital_status, r.religion, r.ethnicity, r.disability_status, r.education_level, r.languages_spoken, r.address_id, r.created_at, r.deleted_at, r.search_vector,
  a.house_number,
  c.name AS city_name,
  k.name AS kebele_name,
  b.blood_type,
  b.face,
  d.type AS document_type,
  d.status AS document_status,
  d.url AS document_url,
  d.number AS document_number,
  e.status AS employment_status,
  e.occupation,
  e.employer_name,
  e.work_address,
  em.name AS emergency_contact_name,
  em.relation AS emergency_contact_relation,
  em.phone AS emergency_contact_phone
FROM resident r
LEFT JOIN address a ON r.address_id = a.id
LEFT JOIN city c ON a.city_id = c.id
LEFT JOIN kebele k ON a.kebele_id = k.id
LEFT JOIN biometric b ON r.id = b.resident_id
LEFT JOIN document d ON r.id = d.resident_id
LEFT JOIN employment e ON r.id = e.resident_id
LEFT JOIN emergency em ON r.id = em.resident_id
WHERE r.id = $1 AND r.deleted_at IS NULL
`

type GetResidentFullRow struct {
	ID                       uuid.UUID   `db:"id" json:"id"`
	Email                    string      `db:"email" json:"email"`
	FirstName                string      `db:"first_name" json:"first_name"`
	SecondName               string      `db:"second_name" json:"second_name"`
	LastName                 string      `db:"last_name" json:"last_name"`
	BirthDate                time.Time   `db:"birth_date" json:"birth_date"`
	Gender                   string      `db:"gender" json:"gender"`
	Phone                    string      `db:"phone" json:"phone"`
	MaritalStatus            string      `db:"marital_status" json:"marital_status"`
	Religion                 string      `db:"religion" json:"religion"`
	Ethnicity                *string     `db:"ethnicity" json:"ethnicity"`
	DisabilityStatus         *string     `db:"disability_status" json:"disability_status"`
	EducationLevel           *string     `db:"education_level" json:"education_level"`
	LanguagesSpoken          string      `db:"languages_spoken" json:"languages_spoken"`
	AddressID                *uuid.UUID  `db:"address_id" json:"address_id"`
	CreatedAt                time.Time   `db:"created_at" json:"created_at"`
	DeletedAt                *time.Time  `db:"deleted_at" json:"deleted_at"`
	SearchVector             *string     `db:"search_vector" json:"search_vector"`
	HouseNumber              *string     `db:"house_number" json:"house_number"`
	CityName                 *string     `db:"city_name" json:"city_name"`
	KebeleName               *string     `db:"kebele_name" json:"kebele_name"`
	BloodType                *string     `db:"blood_type" json:"blood_type"`
	Face                     *string     `db:"face" json:"face"`
	DocumentType             *string     `db:"document_type" json:"document_type"`
	DocumentStatus           *string     `db:"document_status" json:"document_status"`
	DocumentUrl              *string     `db:"document_url" json:"document_url"`
	DocumentNumber           *string     `db:"document_number" json:"document_number"`
	EmploymentStatus         *string     `db:"employment_status" json:"employment_status"`
	Occupation               *string     `db:"occupation" json:"occupation"`
	EmployerName             *string     `db:"employer_name" json:"employer_name"`
	WorkAddress              *string     `db:"work_address" json:"work_address"`
	EmergencyContactName     *string     `db:"emergency_contact_name" json:"emergency_contact_name"`
	EmergencyContactRelation *string     `db:"emergency_contact_relation" json:"emergency_contact_relation"`
	EmergencyContactPhone    pgtype.Text `db:"emergency_contact_phone" json:"emergency_contact_phone"`
}

func (q *Queries) GetResidentFull(ctx context.Context, id uuid.UUID) (GetResidentFullRow, error) {
	row := q.db.QueryRow(ctx, getResidentFull, id)
	var i GetResidentFullRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.SecondName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.Phone,
		&i.MaritalStatus,
		&i.Religion,
		&i.Ethnicity,
		&i.DisabilityStatus,
		&i.EducationLevel,
		&i.LanguagesSpoken,
		&i.AddressID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.HouseNumber,
		&i.CityName,
		&i.KebeleName,
		&i.BloodType,
		&i.Face,
		&i.DocumentType,
		&i.DocumentStatus,
		&i.DocumentUrl,
		&i.DocumentNumber,
		&i.EmploymentStatus,
		&i.Occupation,
		&i.EmployerName,
		&i.WorkAddress,
		&i.EmergencyContactName,
		&i.EmergencyContactRelation,
		&i.EmergencyContactPhone,
	)
	return i, err
}

const searchResidentsByName = `-- name: SearchResidentsByName :many
SELECT id, first_name, second_name, last_name, search_vector
FROM resident
WHERE search_vector @@ to_tsquery('english', $1)
AND deleted_at IS NULL
ORDER BY ts_rank(search_vector, to_tsquery('english', $1)) DESC
`

type SearchResidentsByNameRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	FirstName    string    `db:"first_name" json:"first_name"`
	SecondName   string    `db:"second_name" json:"second_name"`
	LastName     string    `db:"last_name" json:"last_name"`
	SearchVector *string   `db:"search_vector" json:"search_vector"`
}

func (q *Queries) SearchResidentsByName(ctx context.Context, toTsquery string) ([]SearchResidentsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchResidentsByName, toTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchResidentsByNameRow{}
	for rows.Next() {
		var i SearchResidentsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
