// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idcard.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIDCard = `-- name: CreateIDCard :one
INSERT INTO idcard (
    resident_id, number, issue_date, expiry_date, issue_place
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, resident_id, number, issue_date, expiry_date, issue_place, created_at, deleted_at
`

type CreateIDCardParams struct {
	ResidentID uuid.UUID `db:"resident_id" json:"resident_id"`
	Number     string    `db:"number" json:"number"`
	IssueDate  time.Time `db:"issue_date" json:"issue_date"`
	ExpiryDate time.Time `db:"expiry_date" json:"expiry_date"`
	IssuePlace string    `db:"issue_place" json:"issue_place"`
}

func (q *Queries) CreateIDCard(ctx context.Context, arg CreateIDCardParams) (Idcard, error) {
	row := q.db.QueryRow(ctx, createIDCard,
		arg.ResidentID,
		arg.Number,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.IssuePlace,
	)
	var i Idcard
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Number,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IssuePlace,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIDCard = `-- name: DeleteIDCard :exec
UPDATE idcard
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteIDCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIDCard, id)
	return err
}

const getIDCard = `-- name: GetIDCard :one
SELECT id, resident_id, number, issue_date, expiry_date, issue_place, created_at, deleted_at
FROM idcard
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIDCard(ctx context.Context, id uuid.UUID) (Idcard, error) {
	row := q.db.QueryRow(ctx, getIDCard, id)
	var i Idcard
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Number,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IssuePlace,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIDCardByNumber = `-- name: GetIDCardByNumber :one
SELECT id, resident_id, number, issue_date, expiry_date, issue_place, created_at, deleted_at
FROM idcard
WHERE number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIDCardByNumber(ctx context.Context, number string) (Idcard, error) {
	row := q.db.QueryRow(ctx, getIDCardByNumber, number)
	var i Idcard
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Number,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IssuePlace,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIDCardByResident = `-- name: GetIDCardByResident :one
SELECT id, resident_id, number, issue_date, expiry_date, issue_place, created_at, deleted_at
FROM idcard
WHERE resident_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIDCardByResident(ctx context.Context, residentID uuid.UUID) (Idcard, error) {
	row := q.db.QueryRow(ctx, getIDCardByResident, residentID)
	var i Idcard
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Number,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IssuePlace,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteIDCard = `-- name: HardDeleteIDCard :exec
DELETE FROM idcard
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteIDCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteIDCard, id)
	return err
}

const listIDCards = `-- name: ListIDCards :many
SELECT id, resident_id, number, issue_date, expiry_date, issue_place, created_at, deleted_at
FROM idcard
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListIDCardsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListIDCards(ctx context.Context, arg ListIDCardsParams) ([]Idcard, error) {
	rows, err := q.db.Query(ctx, listIDCards, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Idcard{}
	for rows.Next() {
		var i Idcard
		if err := rows.Scan(
			&i.ID,
			&i.ResidentID,
			&i.Number,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.IssuePlace,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIDCard = `-- name: UpdateIDCard :one
UPDATE idcard
SET
    number       = COALESCE($1, number),
    issue_date   = COALESCE($2, issue_date),
    expiry_date  = COALESCE($3, expiry_date),
    issue_place  = COALESCE($4, issue_place)
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, resident_id, number, issue_date, expiry_date, issue_place, created_at, deleted_at
`

type UpdateIDCardParams struct {
	Number     *string    `db:"number" json:"number"`
	IssueDate  *time.Time `db:"issue_date" json:"issue_date"`
	ExpiryDate *time.Time `db:"expiry_date" json:"expiry_date"`
	IssuePlace *string    `db:"issue_place" json:"issue_place"`
	ID         uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateIDCard(ctx context.Context, arg UpdateIDCardParams) (Idcard, error) {
	row := q.db.QueryRow(ctx, updateIDCard,
		arg.Number,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.IssuePlace,
		arg.ID,
	)
	var i Idcard
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Number,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IssuePlace,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
