// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DocumentStatus string

const (
	DocumentStatusPENDING  DocumentStatus = "PENDING"
	DocumentStatusAPPROVED DocumentStatus = "APPROVED"
	DocumentStatusREJECTED DocumentStatus = "REJECTED"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus `json:"document_status"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type DocumentType string

const (
	DocumentTypeID             DocumentType = "ID"
	DocumentTypePASSPORT       DocumentType = "PASSPORT"
	DocumentTypeDRIVINGLICENSE DocumentType = "DRIVING_LICENSE"
	DocumentTypeNATIONALID     DocumentType = "NATIONAL_ID"
	DocumentTypeOTHER          DocumentType = "OTHER"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type Gender string

const (
	GenderMALE   Gender = "MALE"
	GenderFEMALE Gender = "FEMALE"
	GenderOTHER  Gender = "OTHER"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type MaritalStatus string

const (
	MaritalStatusSINGLE   MaritalStatus = "SINGLE"
	MaritalStatusMARRIED  MaritalStatus = "MARRIED"
	MaritalStatusDIVORCED MaritalStatus = "DIVORCED"
	MaritalStatusWIDOWED  MaritalStatus = "WIDOWED"
)

func (e *MaritalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaritalStatus(s)
	case string:
		*e = MaritalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaritalStatus: %T", src)
	}
	return nil
}

type NullMaritalStatus struct {
	MaritalStatus MaritalStatus `json:"marital_status"`
	Valid         bool          `json:"valid"` // Valid is true if MaritalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaritalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaritalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaritalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaritalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaritalStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCASH         PaymentMethod = "CASH"
	PaymentMethodMOBILEMONEY  PaymentMethod = "MOBILE_MONEY"
	PaymentMethodBANKTRANSFER PaymentMethod = "BANK_TRANSFER"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDING  PaymentStatus = "PENDING"
	PaymentStatusAPPROVED PaymentStatus = "APPROVED"
	PaymentStatusREJECTED PaymentStatus = "REJECTED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Religion string

const (
	ReligionCHRISTIAN Religion = "CHRISTIAN"
	ReligionMUSLIM    Religion = "MUSLIM"
	ReligionATHEIST   Religion = "ATHEIST"
	ReligionHINDU     Religion = "HINDU"
	ReligionBUDDHIST  Religion = "BUDDHIST"
	ReligionOTHER     Religion = "OTHER"
	ReligionNONE      Religion = "NONE"
)

func (e *Religion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Religion(s)
	case string:
		*e = Religion(s)
	default:
		return fmt.Errorf("unsupported scan type for Religion: %T", src)
	}
	return nil
}

type NullReligion struct {
	Religion Religion `json:"religion"`
	Valid    bool     `json:"valid"` // Valid is true if Religion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReligion) Scan(value interface{}) error {
	if value == nil {
		ns.Religion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Religion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReligion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Religion), nil
}

type Address struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	HouseNumber string     `db:"house_number" json:"house_number"`
	KebeleID    uuid.UUID  `db:"kebele_id" json:"kebele_id"`
	SubcityID   *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	CityID      uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
}

type AuditLog struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	ActorID        uuid.UUID  `db:"actor_id" json:"actor_id"`
	TargetUserID   *uuid.UUID `db:"target_user_id" json:"target_user_id"`
	TargetRoleSlug *string    `db:"target_role_slug" json:"target_role_slug"`
	ActionType     string     `db:"action_type" json:"action_type"`
	ObjectType     string     `db:"object_type" json:"object_type"`
	ObjectID       *int64     `db:"object_id" json:"object_id"`
	DiffJson       []byte     `db:"diff_json" json:"diff_json"`
	Ts             time.Time  `db:"ts" json:"ts"`
}

type Biometric struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	ResidentID  uuid.UUID  `db:"resident_id" json:"resident_id"`
	Fingerprint []byte     `db:"fingerprint" json:"fingerprint"`
	BloodType   string     `db:"blood_type" json:"blood_type"`
	Face        string     `db:"face" json:"face"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
}

type City struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Document struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	Type       string     `db:"type" json:"type"`
	ResidentID uuid.UUID  `db:"resident_id" json:"resident_id"`
	Url        string     `db:"url" json:"url"`
	Status     string     `db:"status" json:"status"`
	Number     string     `db:"number" json:"number"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Emergency struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	ResidentID uuid.UUID  `db:"resident_id" json:"resident_id"`
	Name       string     `db:"name" json:"name"`
	Relation   string     `db:"relation" json:"relation"`
	Phone      string     `db:"phone" json:"phone"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Employment struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	ResidentID   uuid.UUID  `db:"resident_id" json:"resident_id"`
	Status       string     `db:"status" json:"status"`
	Occupation   *string    `db:"occupation" json:"occupation"`
	EmployerName *string    `db:"employer_name" json:"employer_name"`
	WorkAddress  *string    `db:"work_address" json:"work_address"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Idcard struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	ResidentID uuid.UUID  `db:"resident_id" json:"resident_id"`
	Number     string     `db:"number" json:"number"`
	IssueDate  time.Time  `db:"issue_date" json:"issue_date"`
	ExpiryDate time.Time  `db:"expiry_date" json:"expiry_date"`
	IssuePlace string     `db:"issue_place" json:"issue_place"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Kebele struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	SubcityID *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	CityID    uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Payment struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	ResidentID  uuid.UUID  `db:"resident_id" json:"resident_id"`
	Amount      float64    `db:"amount" json:"amount"`
	Description string     `db:"description" json:"description"`
	Status      string     `db:"status" json:"status"`
	Reference   string     `db:"reference" json:"reference"`
	Method      string     `db:"method" json:"method"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Permission struct {
	Name        string  `db:"name" json:"name"`
	Label       string  `db:"label" json:"label"`
	Description *string `db:"description" json:"description"`
}

type RefreshTokens struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Resident struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	Email            string     `db:"email" json:"email"`
	FirstName        string     `db:"first_name" json:"first_name"`
	SecondName       string     `db:"second_name" json:"second_name"`
	LastName         string     `db:"last_name" json:"last_name"`
	BirthDate        time.Time  `db:"birth_date" json:"birth_date"`
	Gender           string     `db:"gender" json:"gender"`
	Phone            string     `db:"phone" json:"phone"`
	MaritalStatus    string     `db:"marital_status" json:"marital_status"`
	Religion         string     `db:"religion" json:"religion"`
	Ethnicity        *string    `db:"ethnicity" json:"ethnicity"`
	DisabilityStatus *string    `db:"disability_status" json:"disability_status"`
	EducationLevel   *string    `db:"education_level" json:"education_level"`
	LanguagesSpoken  string     `db:"languages_spoken" json:"languages_spoken"`
	AddressID        *uuid.UUID `db:"address_id" json:"address_id"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
	DeletedAt        *time.Time `db:"deleted_at" json:"deleted_at"`
}

type Role struct {
	Slug           string  `db:"slug" json:"slug"`
	Name           string  `db:"name" json:"name"`
	ParentRoleSlug *string `db:"parent_role_slug" json:"parent_role_slug"`
	LevelRank      int32   `db:"level_rank" json:"level_rank"`
}

type RolePermission struct {
	RoleSlug       string `db:"role_slug" json:"role_slug"`
	PermissionName string `db:"permission_name" json:"permission_name"`
}

type Subcity struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	CityID    uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	FirstName    string     `db:"first_name" json:"first_name"`
	SecondName   string     `db:"second_name" json:"second_name"`
	LastName     string     `db:"last_name" json:"last_name"`
	Email        string     `db:"email" json:"email"`
	Phone        string     `db:"phone" json:"phone"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	CityID       *uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID    *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID     *uuid.UUID `db:"kebele_id" json:"kebele_id"`
	RoleSlug     string     `db:"role_slug" json:"role_slug"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
}

type UserPermissionOverride struct {
	UserID         uuid.UUID  `db:"user_id" json:"user_id"`
	PermissionName string     `db:"permission_name" json:"permission_name"`
	IsGranted      bool       `db:"is_granted" json:"is_granted"`
	GrantedBy      *uuid.UUID `db:"granted_by" json:"granted_by"`
	GrantedAt      time.Time  `db:"granted_at" json:"granted_at"`
}
