// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (
    resident_id, amount, description, status, reference, method
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, resident_id, amount, description, status, reference, method, created_at, deleted_at
`

type CreatePaymentParams struct {
	ResidentID  uuid.UUID     `db:"resident_id" json:"resident_id"`
	Amount      float64       `db:"amount" json:"amount"`
	Description string        `db:"description" json:"description"`
	Status      PaymentStatus `db:"status" json:"status"`
	Reference   string        `db:"reference" json:"reference"`
	Method      PaymentMethod `db:"method" json:"method"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ResidentID,
		arg.Amount,
		arg.Description,
		arg.Status,
		arg.Reference,
		arg.Method,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Reference,
		&i.Method,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
UPDATE payment
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, resident_id, amount, description, status, reference, method, created_at, deleted_at
FROM payment
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Reference,
		&i.Method,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentByResident = `-- name: GetPaymentByResident :one
SELECT id, resident_id, amount, description, status, reference, method, created_at, deleted_at
FROM payment
WHERE resident_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentByResident(ctx context.Context, residentID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByResident, residentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Reference,
		&i.Method,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeletePayment = `-- name: HardDeletePayment :exec
DELETE FROM payment
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeletePayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeletePayment, id)
	return err
}

const listPayments = `-- name: ListPayments :many
SELECT id, resident_id, amount, description, status, reference, method, created_at, deleted_at
FROM payment
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListPaymentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ResidentID,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.Reference,
			&i.Method,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payment
SET
    amount      = COALESCE($1, amount),
    description = COALESCE($2, description),
    status      = COALESCE($3, status),
    reference   = COALESCE($4, reference),
    method      = COALESCE($5, method)
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, resident_id, amount, description, status, reference, method, created_at, deleted_at
`

type UpdatePaymentParams struct {
	Amount      *float64          `db:"amount" json:"amount"`
	Description *string           `db:"description" json:"description"`
	Status      NullPaymentStatus `db:"status" json:"status"`
	Reference   *string           `db:"reference" json:"reference"`
	Method      NullPaymentMethod `db:"method" json:"method"`
	ID          uuid.UUID         `db:"id" json:"id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.Amount,
		arg.Description,
		arg.Status,
		arg.Reference,
		arg.Method,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ResidentID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Reference,
		&i.Method,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
