// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permission.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEffectivePermissionsForUser = `-- name: GetEffectivePermissionsForUser :many
WITH RECURSIVE role_tree AS (
    -- start from the user’s role
    SELECT r.slug, r.level_rank
    FROM role r
    WHERE r.slug = (SELECT role_slug FROM "user" WHERE id = $1)
    UNION
    SELECT r.slug, r.level_rank
    FROM role r
    JOIN role_tree rt ON r.parent_role_slug = rt.slug
),
inherited AS (
    SELECT DISTINCT rp.permission_name
    FROM role_permission rp
    WHERE rp.role_slug IN (SELECT slug FROM role_tree)
),
overrides AS (
    SELECT permission_name, is_granted
    FROM user_permission_override
    WHERE user_id = $1
)
SELECT
    p.name,
    p.label,
    p.description,
    COALESCE(o.is_granted, true) AS effective,
    o.is_granted IS NOT NULL     AS overridden
FROM permission p
LEFT JOIN inherited i ON i.permission_name = p.name
LEFT JOIN overrides o ON o.permission_name = p.name
WHERE o.is_granted = true
   OR (o.is_granted IS NULL AND i.permission_name IS NOT NULL)
ORDER BY p.name
`

type GetEffectivePermissionsForUserRow struct {
	Name        string      `db:"name" json:"name"`
	Label       string      `db:"label" json:"label"`
	Description *string     `db:"description" json:"description"`
	Effective   bool        `db:"effective" json:"effective"`
	Overridden  interface{} `db:"overridden" json:"overridden"`
}

func (q *Queries) GetEffectivePermissionsForUser(ctx context.Context, id uuid.UUID) ([]GetEffectivePermissionsForUserRow, error) {
	rows, err := q.db.Query(ctx, getEffectivePermissionsForUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEffectivePermissionsForUserRow{}
	for rows.Next() {
		var i GetEffectivePermissionsForUserRow
		if err := rows.Scan(
			&i.Name,
			&i.Label,
			&i.Description,
			&i.Effective,
			&i.Overridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :exec
INSERT INTO role_permission (role_slug, permission_name)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantPermissionToRoleParams struct {
	RoleSlug       string `db:"role_slug" json:"role_slug"`
	PermissionName string `db:"permission_name" json:"permission_name"`
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, grantPermissionToRole, arg.RoleSlug, arg.PermissionName)
	return err
}

const listPermissionOverridesForUser = `-- name: ListPermissionOverridesForUser :many
SELECT permission_name, is_granted, granted_by, granted_at
FROM user_permission_override
WHERE user_id = $1
ORDER BY permission_name
`

type ListPermissionOverridesForUserRow struct {
	PermissionName string     `db:"permission_name" json:"permission_name"`
	IsGranted      bool       `db:"is_granted" json:"is_granted"`
	GrantedBy      *uuid.UUID `db:"granted_by" json:"granted_by"`
	GrantedAt      time.Time  `db:"granted_at" json:"granted_at"`
}

func (q *Queries) ListPermissionOverridesForUser(ctx context.Context, userID uuid.UUID) ([]ListPermissionOverridesForUserRow, error) {
	rows, err := q.db.Query(ctx, listPermissionOverridesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionOverridesForUserRow{}
	for rows.Next() {
		var i ListPermissionOverridesForUserRow
		if err := rows.Scan(
			&i.PermissionName,
			&i.IsGranted,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT name, label, description FROM permission ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Name, &i.Label, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserPermissionOverride = `-- name: RemoveUserPermissionOverride :exec
DELETE FROM user_permission_override
WHERE user_id = $1 AND permission_name = $2
`

type RemoveUserPermissionOverrideParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	PermissionName string    `db:"permission_name" json:"permission_name"`
}

func (q *Queries) RemoveUserPermissionOverride(ctx context.Context, arg RemoveUserPermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, removeUserPermissionOverride, arg.UserID, arg.PermissionName)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permission
WHERE role_slug = $1 AND permission_name = $2
`

type RevokePermissionFromRoleParams struct {
	RoleSlug       string `db:"role_slug" json:"role_slug"`
	PermissionName string `db:"permission_name" json:"permission_name"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleSlug, arg.PermissionName)
	return err
}

const setUserPermissionOverride = `-- name: SetUserPermissionOverride :exec
INSERT INTO user_permission_override (user_id, permission_name, is_granted, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, permission_name)
DO UPDATE SET is_granted = EXCLUDED.is_granted, granted_by = EXCLUDED.granted_by, granted_at = now()
`

type SetUserPermissionOverrideParams struct {
	UserID         uuid.UUID  `db:"user_id" json:"user_id"`
	PermissionName string     `db:"permission_name" json:"permission_name"`
	IsGranted      bool       `db:"is_granted" json:"is_granted"`
	GrantedBy      *uuid.UUID `db:"granted_by" json:"granted_by"`
}

func (q *Queries) SetUserPermissionOverride(ctx context.Context, arg SetUserPermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, setUserPermissionOverride,
		arg.UserID,
		arg.PermissionName,
		arg.IsGranted,
		arg.GrantedBy,
	)
	return err
}
