// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (uuid.UUID, error)
	CreateBiometric(ctx context.Context, arg CreateBiometricParams) error
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) error
	CreateEmergency(ctx context.Context, arg CreateEmergencyParams) error
	CreateEmployment(ctx context.Context, arg CreateEmploymentParams) error
	CreateKebele(ctx context.Context, arg CreateKebeleParams) (Kebele, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateResident(ctx context.Context, arg CreateResidentParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokensByUser(ctx context.Context, userID uuid.UUID) error
	GetAddress(ctx context.Context, arg GetAddressParams) (Address, error)
	GetAllResidents(ctx context.Context) ([]GetAllResidentsRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshTokens, error)
	GetResidentFull(ctx context.Context, id uuid.UUID) (GetResidentFullRow, error)
	GetUserByEmail(ctx context.Context, email string) (Actor, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (Actor, error)
	SearchResidentsByName(ctx context.Context, toTsquery string) ([]SearchResidentsByNameRow, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateResidentAddress(ctx context.Context, arg UpdateResidentAddressParams) error
}

var _ Querier = (*Queries)(nil)
