// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: register_resident.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createResident = `-- name: CreateResident :one
INSERT INTO resident (
  email, first_name, second_name, last_name, birth_date, gender, phone,
  marital_status, religion, ethnicity, disability_status, education_level,
  languages_spoken, address_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13, $14
)
RETURNING id
`

type CreateResidentParams struct {
	Email            string     `db:"email" json:"email"`
	FirstName        string     `db:"first_name" json:"first_name"`
	SecondName       string     `db:"second_name" json:"second_name"`
	LastName         string     `db:"last_name" json:"last_name"`
	BirthDate        time.Time  `db:"birth_date" json:"birth_date"`
	Gender           string     `db:"gender" json:"gender"`
	Phone            string     `db:"phone" json:"phone"`
	MaritalStatus    string     `db:"marital_status" json:"marital_status"`
	Religion         string     `db:"religion" json:"religion"`
	Ethnicity        *string    `db:"ethnicity" json:"ethnicity"`
	DisabilityStatus *string    `db:"disability_status" json:"disability_status"`
	EducationLevel   *string    `db:"education_level" json:"education_level"`
	LanguagesSpoken  string     `db:"languages_spoken" json:"languages_spoken"`
	AddressID        *uuid.UUID `db:"address_id" json:"address_id"`
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createResident,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
		arg.MaritalStatus,
		arg.Religion,
		arg.Ethnicity,
		arg.DisabilityStatus,
		arg.EducationLevel,
		arg.LanguagesSpoken,
		arg.AddressID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateResidentAddress = `-- name: UpdateResidentAddress :exec
UPDATE resident SET address_id = $1 WHERE id = $2
`

type UpdateResidentAddressParams struct {
	AddressID *uuid.UUID `db:"address_id" json:"address_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateResidentAddress(ctx context.Context, arg UpdateResidentAddressParams) error {
	_, err := q.db.Exec(ctx, updateResidentAddress, arg.AddressID, arg.ID)
	return err
}
