// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resident.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListResidents = `-- name: CountListResidents :one
SELECT COUNT(*)
FROM resident r
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
)
`

func (q *Queries) CountListResidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListResidents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListUnpaidResidents = `-- name: CountListUnpaidResidents :one
SELECT COUNT(*)
FROM resident r
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status != 'verified'
`

func (q *Queries) CountListUnpaidResidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListUnpaidResidents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListUnverifiedResidents = `-- name: CountListUnverifiedResidents :one
SELECT COUNT(*)
FROM resident r
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND NOT EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
)
`

func (q *Queries) CountListUnverifiedResidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListUnverifiedResidents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchResidents = `-- name: CountSearchResidents :one
SELECT COUNT(*)
FROM resident r
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified' 
AND EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
) AND similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) > 0.2
`

func (q *Queries) CountSearchResidents(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchResidents, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUnpaidResidents = `-- name: CountSearchUnpaidResidents :one
SELECT COUNT(*)
FROM resident r
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status != 'verified' AND
    similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) > 0.2
`

func (q *Queries) CountSearchUnpaidResidents(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUnpaidResidents, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUnverifiedResidents = `-- name: CountSearchUnverifiedResidents :one
SELECT COUNT(*)
FROM resident r
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND NOT EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
) AND similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) > 0.2
`

func (q *Queries) CountSearchUnverifiedResidents(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUnverifiedResidents, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResident = `-- name: CreateResident :one
INSERT INTO resident (
  email, first_name, second_name, last_name, birth_date, gender, phone, address_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateResidentParams struct {
	Email      string     `db:"email" json:"email"`
	FirstName  string     `db:"first_name" json:"first_name"`
	SecondName string     `db:"second_name" json:"second_name"`
	LastName   string     `db:"last_name" json:"last_name"`
	BirthDate  time.Time  `db:"birth_date" json:"birth_date"`
	Gender     string     `db:"gender" json:"gender"`
	Phone      string     `db:"phone" json:"phone"`
	AddressID  *uuid.UUID `db:"address_id" json:"address_id"`
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createResident,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
		arg.AddressID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllResidents = `-- name: DeleteAllResidents :exec
DELETE FROM resident
`

func (q *Queries) DeleteAllResidents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllResidents)
	return err
}

const deleteResident = `-- name: DeleteResident :exec
DELETE FROM resident WHERE id = $1
`

func (q *Queries) DeleteResident(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResident, id)
	return err
}

const getResident = `-- name: GetResident :one
SELECT resident.id, resident.email, resident.first_name, resident.second_name, resident.last_name, resident.birth_date, resident.gender, resident.phone, resident.address_id, resident.created_at, resident.deleted_at, address.id, address.house_number, address.kebele_id, address.subcity_id, address.city_id, address.created_at, address.deleted_at, biometric.id, biometric.resident_id, biometric.fingerprint, biometric.blood_type, biometric.face_url, biometric.created_at, biometric.deleted_at,
    additional.id, additional.resident_id, additional.marital_status, additional.religion, additional.ethnicity, additional.disability, additional.national_id, additional.education_level, additional.languages_spoken, additional.created_at, additional.deleted_at, employment.id, employment.resident_id, employment.status, employment.type, employment.occupation, employment.employer_name, employment.work_address, employment.created_at, employment.deleted_at, emergency.id, emergency.resident_id, emergency.name, emergency.relation, emergency.phone, emergency.email, emergency.created_at, emergency.deleted_at
FROM resident
JOIN address    ON resident.address_id = address.id
JOIN biometric  ON resident.id = biometric.resident_id
JOIN document   ON resident.id = document.resident_id
JOIN employment ON resident.id = employment.resident_id
JOIN emergency  ON resident.id = emergency.resident_id
JOIN additional ON resident.id = additional.resident_id
WHERE resident.id = $1
`

type GetResidentRow struct {
	Resident   Resident   `db:"resident" json:"resident"`
	Address    Address    `db:"address" json:"address"`
	Biometric  Biometric  `db:"biometric" json:"biometric"`
	Additional Additional `db:"additional" json:"additional"`
	Employment Employment `db:"employment" json:"employment"`
	Emergency  Emergency  `db:"emergency" json:"emergency"`
}

func (q *Queries) GetResident(ctx context.Context, id uuid.UUID) (GetResidentRow, error) {
	row := q.db.QueryRow(ctx, getResident, id)
	var i GetResidentRow
	err := row.Scan(
		&i.Resident.ID,
		&i.Resident.Email,
		&i.Resident.FirstName,
		&i.Resident.SecondName,
		&i.Resident.LastName,
		&i.Resident.BirthDate,
		&i.Resident.Gender,
		&i.Resident.Phone,
		&i.Resident.AddressID,
		&i.Resident.CreatedAt,
		&i.Resident.DeletedAt,
		&i.Address.ID,
		&i.Address.HouseNumber,
		&i.Address.KebeleID,
		&i.Address.SubcityID,
		&i.Address.CityID,
		&i.Address.CreatedAt,
		&i.Address.DeletedAt,
		&i.Biometric.ID,
		&i.Biometric.ResidentID,
		&i.Biometric.Fingerprint,
		&i.Biometric.BloodType,
		&i.Biometric.FaceUrl,
		&i.Biometric.CreatedAt,
		&i.Biometric.DeletedAt,
		&i.Additional.ID,
		&i.Additional.ResidentID,
		&i.Additional.MaritalStatus,
		&i.Additional.Religion,
		&i.Additional.Ethnicity,
		&i.Additional.Disability,
		&i.Additional.NationalID,
		&i.Additional.EducationLevel,
		&i.Additional.LanguagesSpoken,
		&i.Additional.CreatedAt,
		&i.Additional.DeletedAt,
		&i.Employment.ID,
		&i.Employment.ResidentID,
		&i.Employment.Status,
		&i.Employment.Type,
		&i.Employment.Occupation,
		&i.Employment.EmployerName,
		&i.Employment.WorkAddress,
		&i.Employment.CreatedAt,
		&i.Employment.DeletedAt,
		&i.Emergency.ID,
		&i.Emergency.ResidentID,
		&i.Emergency.Name,
		&i.Emergency.Relation,
		&i.Emergency.Phone,
		&i.Emergency.Email,
		&i.Emergency.CreatedAt,
		&i.Emergency.DeletedAt,
	)
	return i, err
}

const listResidents = `-- name: ListResidents :many
SELECT r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.address_id, r.created_at, r.deleted_at, b.face_url, CONCAT_WS(' ', r.first_name, r.second_name, r.last_name) AS full_name
FROM resident r
JOIN biometric b   ON r.id = b.resident_id
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
)
ORDER BY r.created_at ASC
LIMIT $2 OFFSET $1
`

type ListResidentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListResidentsRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	Email      string     `db:"email" json:"email"`
	FirstName  string     `db:"first_name" json:"first_name"`
	SecondName string     `db:"second_name" json:"second_name"`
	LastName   string     `db:"last_name" json:"last_name"`
	BirthDate  time.Time  `db:"birth_date" json:"birth_date"`
	Gender     string     `db:"gender" json:"gender"`
	Phone      string     `db:"phone" json:"phone"`
	AddressID  *uuid.UUID `db:"address_id" json:"address_id"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
	FaceUrl    string     `db:"face_url" json:"face_url"`
	FullName   string     `db:"full_name" json:"full_name"`
}

func (q *Queries) ListResidents(ctx context.Context, arg ListResidentsParams) ([]ListResidentsRow, error) {
	rows, err := q.db.Query(ctx, listResidents, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResidentsRow{}
	for rows.Next() {
		var i ListResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.AddressID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FaceUrl,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidResidents = `-- name: ListUnpaidResidents :many
SELECT r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.address_id, r.created_at, r.deleted_at, p.id, p.resident_id, p.amount, p.description, p.status, p.reference, p.method, p.created_at, p.deleted_at, b.face_url, CONCAT_WS(' ', r.first_name, r.second_name, r.last_name) AS full_name
FROM resident r
JOIN biometric b   ON r.id = b.resident_id
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status != 'verified'
ORDER BY r.created_at ASC
LIMIT $2 OFFSET $1
`

type ListUnpaidResidentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListUnpaidResidentsRow struct {
	Resident Resident `db:"resident" json:"resident"`
	Payment  Payment  `db:"payment" json:"payment"`
	FaceUrl  string   `db:"face_url" json:"face_url"`
	FullName string   `db:"full_name" json:"full_name"`
}

func (q *Queries) ListUnpaidResidents(ctx context.Context, arg ListUnpaidResidentsParams) ([]ListUnpaidResidentsRow, error) {
	rows, err := q.db.Query(ctx, listUnpaidResidents, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnpaidResidentsRow{}
	for rows.Next() {
		var i ListUnpaidResidentsRow
		if err := rows.Scan(
			&i.Resident.ID,
			&i.Resident.Email,
			&i.Resident.FirstName,
			&i.Resident.SecondName,
			&i.Resident.LastName,
			&i.Resident.BirthDate,
			&i.Resident.Gender,
			&i.Resident.Phone,
			&i.Resident.AddressID,
			&i.Resident.CreatedAt,
			&i.Resident.DeletedAt,
			&i.Payment.ID,
			&i.Payment.ResidentID,
			&i.Payment.Amount,
			&i.Payment.Description,
			&i.Payment.Status,
			&i.Payment.Reference,
			&i.Payment.Method,
			&i.Payment.CreatedAt,
			&i.Payment.DeletedAt,
			&i.FaceUrl,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnverifiedResidents = `-- name: ListUnverifiedResidents :many
SELECT 
    r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.address_id, r.created_at, r.deleted_at, p.id, p.resident_id, p.amount, p.description, p.status, p.reference, p.method, p.created_at, p.deleted_at, b.face_url,
    CONCAT_WS(' ', r.first_name, r.second_name, r.last_name) AS full_name,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM document d 
            WHERE d.resident_id = r.id AND d.status = 'pending'
        ) THEN 'pending'
        WHEN EXISTS (
            SELECT 1 FROM document d 
            WHERE d.resident_id = r.id AND d.status = 'rejected'
        ) THEN 'rejected'
        ELSE 'no documents'
    END AS status
FROM resident r
JOIN biometric b   ON r.id = b.resident_id
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND NOT EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
)
ORDER BY r.created_at ASC
LIMIT $2 OFFSET $1
`

type ListUnverifiedResidentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListUnverifiedResidentsRow struct {
	Resident Resident `db:"resident" json:"resident"`
	Payment  Payment  `db:"payment" json:"payment"`
	FaceUrl  string   `db:"face_url" json:"face_url"`
	FullName string   `db:"full_name" json:"full_name"`
	Status   string   `db:"status" json:"status"`
}

func (q *Queries) ListUnverifiedResidents(ctx context.Context, arg ListUnverifiedResidentsParams) ([]ListUnverifiedResidentsRow, error) {
	rows, err := q.db.Query(ctx, listUnverifiedResidents, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnverifiedResidentsRow{}
	for rows.Next() {
		var i ListUnverifiedResidentsRow
		if err := rows.Scan(
			&i.Resident.ID,
			&i.Resident.Email,
			&i.Resident.FirstName,
			&i.Resident.SecondName,
			&i.Resident.LastName,
			&i.Resident.BirthDate,
			&i.Resident.Gender,
			&i.Resident.Phone,
			&i.Resident.AddressID,
			&i.Resident.CreatedAt,
			&i.Resident.DeletedAt,
			&i.Payment.ID,
			&i.Payment.ResidentID,
			&i.Payment.Amount,
			&i.Payment.Description,
			&i.Payment.Status,
			&i.Payment.Reference,
			&i.Payment.Method,
			&i.Payment.CreatedAt,
			&i.Payment.DeletedAt,
			&i.FaceUrl,
			&i.FullName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchResidents = `-- name: SearchResidents :many
SELECT r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.address_id, r.created_at, r.deleted_at, b.face_url, CONCAT_WS(' ', r.first_name, r.second_name, r.last_name) AS full_name,
    similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) AS sim
FROM resident r
JOIN biometric b   ON r.id = b.resident_id
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
) AND similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) > 0.2
ORDER BY sim DESC, r.created_at ASC
LIMIT $3 OFFSET $2
`

type SearchResidentsParams struct {
	Query  string `db:"query" json:"query"`
	Offset int32  `db:"offset" json:"offset"`
	Limit  int32  `db:"limit" json:"limit"`
}

type SearchResidentsRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	Email      string     `db:"email" json:"email"`
	FirstName  string     `db:"first_name" json:"first_name"`
	SecondName string     `db:"second_name" json:"second_name"`
	LastName   string     `db:"last_name" json:"last_name"`
	BirthDate  time.Time  `db:"birth_date" json:"birth_date"`
	Gender     string     `db:"gender" json:"gender"`
	Phone      string     `db:"phone" json:"phone"`
	AddressID  *uuid.UUID `db:"address_id" json:"address_id"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
	FaceUrl    string     `db:"face_url" json:"face_url"`
	FullName   string     `db:"full_name" json:"full_name"`
	Sim        float32    `db:"sim" json:"sim"`
}

func (q *Queries) SearchResidents(ctx context.Context, arg SearchResidentsParams) ([]SearchResidentsRow, error) {
	rows, err := q.db.Query(ctx, searchResidents, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchResidentsRow{}
	for rows.Next() {
		var i SearchResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.AddressID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FaceUrl,
			&i.FullName,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUnpaidResidents = `-- name: SearchUnpaidResidents :many
SELECT r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.address_id, r.created_at, r.deleted_at, p.id, p.resident_id, p.amount, p.description, p.status, p.reference, p.method, p.created_at, p.deleted_at, b.face_url, CONCAT_WS(' ', r.first_name, r.second_name, r.last_name) AS full_name,
    similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) AS sim
FROM resident r
JOIN biometric b   ON r.id = b.resident_id
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status != 'verified' AND
    similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) > 0.2
ORDER BY r.created_at ASC
LIMIT $3 OFFSET $2
`

type SearchUnpaidResidentsParams struct {
	Query  string `db:"query" json:"query"`
	Offset int32  `db:"offset" json:"offset"`
	Limit  int32  `db:"limit" json:"limit"`
}

type SearchUnpaidResidentsRow struct {
	Resident Resident `db:"resident" json:"resident"`
	Payment  Payment  `db:"payment" json:"payment"`
	FaceUrl  string   `db:"face_url" json:"face_url"`
	FullName string   `db:"full_name" json:"full_name"`
	Sim      float32  `db:"sim" json:"sim"`
}

func (q *Queries) SearchUnpaidResidents(ctx context.Context, arg SearchUnpaidResidentsParams) ([]SearchUnpaidResidentsRow, error) {
	rows, err := q.db.Query(ctx, searchUnpaidResidents, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUnpaidResidentsRow{}
	for rows.Next() {
		var i SearchUnpaidResidentsRow
		if err := rows.Scan(
			&i.Resident.ID,
			&i.Resident.Email,
			&i.Resident.FirstName,
			&i.Resident.SecondName,
			&i.Resident.LastName,
			&i.Resident.BirthDate,
			&i.Resident.Gender,
			&i.Resident.Phone,
			&i.Resident.AddressID,
			&i.Resident.CreatedAt,
			&i.Resident.DeletedAt,
			&i.Payment.ID,
			&i.Payment.ResidentID,
			&i.Payment.Amount,
			&i.Payment.Description,
			&i.Payment.Status,
			&i.Payment.Reference,
			&i.Payment.Method,
			&i.Payment.CreatedAt,
			&i.Payment.DeletedAt,
			&i.FaceUrl,
			&i.FullName,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUnverifiedResidents = `-- name: SearchUnverifiedResidents :many
SELECT 
    r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.address_id, r.created_at, r.deleted_at, p.id, p.resident_id, p.amount, p.description, p.status, p.reference, p.method, p.created_at, p.deleted_at, b.face_url,
    CONCAT_WS(' ', r.first_name, r.second_name, r.last_name) AS full_name,
    similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) AS sim,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM document d 
            WHERE d.resident_id = r.id AND d.status = 'pending'
        ) THEN 'pending'
        WHEN EXISTS (
            SELECT 1 FROM document d 
            WHERE d.resident_id = r.id AND d.status = 'rejected'
        ) THEN 'rejected'
        ELSE 'no documents'
    END AS status
FROM resident r
JOIN biometric b   ON r.id = b.resident_id
JOIN payment p     ON p.resident_id = r.id
WHERE r.deleted_at IS NULL AND p.status = 'verified'
AND NOT EXISTS (
    SELECT 1 FROM document d 
    WHERE d.resident_id = r.id AND d.status = 'verified'
) AND similarity(CONCAT_WS(' ', r.first_name, r.second_name, r.last_name), $1) > 0.2
ORDER BY r.created_at ASC
LIMIT $3 OFFSET $2
`

type SearchUnverifiedResidentsParams struct {
	Query  string `db:"query" json:"query"`
	Offset int32  `db:"offset" json:"offset"`
	Limit  int32  `db:"limit" json:"limit"`
}

type SearchUnverifiedResidentsRow struct {
	Resident Resident `db:"resident" json:"resident"`
	Payment  Payment  `db:"payment" json:"payment"`
	FaceUrl  string   `db:"face_url" json:"face_url"`
	FullName string   `db:"full_name" json:"full_name"`
	Sim      float32  `db:"sim" json:"sim"`
	Status   string   `db:"status" json:"status"`
}

func (q *Queries) SearchUnverifiedResidents(ctx context.Context, arg SearchUnverifiedResidentsParams) ([]SearchUnverifiedResidentsRow, error) {
	rows, err := q.db.Query(ctx, searchUnverifiedResidents, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUnverifiedResidentsRow{}
	for rows.Next() {
		var i SearchUnverifiedResidentsRow
		if err := rows.Scan(
			&i.Resident.ID,
			&i.Resident.Email,
			&i.Resident.FirstName,
			&i.Resident.SecondName,
			&i.Resident.LastName,
			&i.Resident.BirthDate,
			&i.Resident.Gender,
			&i.Resident.Phone,
			&i.Resident.AddressID,
			&i.Resident.CreatedAt,
			&i.Resident.DeletedAt,
			&i.Payment.ID,
			&i.Payment.ResidentID,
			&i.Payment.Amount,
			&i.Payment.Description,
			&i.Payment.Status,
			&i.Payment.Reference,
			&i.Payment.Method,
			&i.Payment.CreatedAt,
			&i.Payment.DeletedAt,
			&i.FaceUrl,
			&i.FullName,
			&i.Sim,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResident = `-- name: UpdateResident :exec
UPDATE resident SET
  email = $2, first_name = $3, second_name = $4, last_name = $5,
  birth_date = $6, gender = $7, phone = $8
WHERE id = $1
`

type UpdateResidentParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Email      string    `db:"email" json:"email"`
	FirstName  string    `db:"first_name" json:"first_name"`
	SecondName string    `db:"second_name" json:"second_name"`
	LastName   string    `db:"last_name" json:"last_name"`
	BirthDate  time.Time `db:"birth_date" json:"birth_date"`
	Gender     string    `db:"gender" json:"gender"`
	Phone      string    `db:"phone" json:"phone"`
}

func (q *Queries) UpdateResident(ctx context.Context, arg UpdateResidentParams) error {
	_, err := q.db.Exec(ctx, updateResident,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
	)
	return err
}

const updateResidentAddress = `-- name: UpdateResidentAddress :exec
UPDATE resident SET address_id = $1 WHERE id = $2
`

type UpdateResidentAddressParams struct {
	AddressID *uuid.UUID `db:"address_id" json:"address_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateResidentAddress(ctx context.Context, arg UpdateResidentAddressParams) error {
	_, err := q.db.Exec(ctx, updateResidentAddress, arg.AddressID, arg.ID)
	return err
}
