// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resident.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListResidents = `-- name: CountListResidents :one
SELECT COUNT(*)
FROM resident
WHERE deleted_at IS NULL
`

func (q *Queries) CountListResidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListResidents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchResidents = `-- name: CountSearchResidents :one
SELECT COUNT(*)
FROM resident
WHERE deleted_at IS NULL AND
    similarity(CONCAT_WS(' ', first_name, second_name, last_name), $1) > 0.2
`

func (q *Queries) CountSearchResidents(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchResidents, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResident = `-- name: CreateResident :one
INSERT INTO resident (
  email, first_name, second_name, last_name, birth_date, gender, phone, address_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateResidentParams struct {
	Email      string     `db:"email" json:"email"`
	FirstName  string     `db:"first_name" json:"first_name"`
	SecondName string     `db:"second_name" json:"second_name"`
	LastName   string     `db:"last_name" json:"last_name"`
	BirthDate  time.Time  `db:"birth_date" json:"birth_date"`
	Gender     string     `db:"gender" json:"gender"`
	Phone      string     `db:"phone" json:"phone"`
	AddressID  *uuid.UUID `db:"address_id" json:"address_id"`
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createResident,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
		arg.AddressID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllResidents = `-- name: DeleteAllResidents :exec
DELETE FROM resident
`

func (q *Queries) DeleteAllResidents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllResidents)
	return err
}

const deleteResident = `-- name: DeleteResident :exec
DELETE FROM resident WHERE id = $1
`

func (q *Queries) DeleteResident(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResident, id)
	return err
}

const getResident = `-- name: GetResident :one
SELECT resident.id, resident.email, resident.first_name, resident.second_name, resident.last_name, resident.birth_date, resident.gender, resident.phone, resident.address_id, resident.created_at, resident.deleted_at
    -- sqlc.embed(address), sqlc.embed(biometric), sqlc.embed(document),
    -- sqlc.embed(employment), sqlc.embed(emergency), sqlc.embed(idcard)
FROM resident
WHERE resident.id = $1
`

type GetResidentRow struct {
	Resident Resident `db:"resident" json:"resident"`
}

// LEFT JOIN address    ON resident.address_id = address.id
// LEFT JOIN biometric  ON resident.id = biometric.resident_id
// LEFT JOIN document   ON resident.id = document.resident_id
// LEFT JOIN employment ON resident.id = employment.resident_id
// LEFT JOIN emergency  ON resident.id = emergency.resident_id
// LEFT JOIN idcard     ON resident.id = idcard.resident_id
func (q *Queries) GetResident(ctx context.Context, id uuid.UUID) (GetResidentRow, error) {
	row := q.db.QueryRow(ctx, getResident, id)
	var i GetResidentRow
	err := row.Scan(
		&i.Resident.ID,
		&i.Resident.Email,
		&i.Resident.FirstName,
		&i.Resident.SecondName,
		&i.Resident.LastName,
		&i.Resident.BirthDate,
		&i.Resident.Gender,
		&i.Resident.Phone,
		&i.Resident.AddressID,
		&i.Resident.CreatedAt,
		&i.Resident.DeletedAt,
	)
	return i, err
}

const listResidents = `-- name: ListResidents :many
SELECT id, email, first_name, second_name, last_name, birth_date, gender, phone, address_id, created_at, deleted_at, CONCAT_WS(' ', first_name, second_name, last_name) AS full_name
FROM resident
WHERE deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $1
`

type ListResidentsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListResidentsRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	Email      string     `db:"email" json:"email"`
	FirstName  string     `db:"first_name" json:"first_name"`
	SecondName string     `db:"second_name" json:"second_name"`
	LastName   string     `db:"last_name" json:"last_name"`
	BirthDate  time.Time  `db:"birth_date" json:"birth_date"`
	Gender     string     `db:"gender" json:"gender"`
	Phone      string     `db:"phone" json:"phone"`
	AddressID  *uuid.UUID `db:"address_id" json:"address_id"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
	FullName   string     `db:"full_name" json:"full_name"`
}

func (q *Queries) ListResidents(ctx context.Context, arg ListResidentsParams) ([]ListResidentsRow, error) {
	rows, err := q.db.Query(ctx, listResidents, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResidentsRow{}
	for rows.Next() {
		var i ListResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.AddressID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchResidents = `-- name: SearchResidents :many
SELECT id, email, first_name, second_name, last_name, birth_date, gender, phone, address_id, created_at, deleted_at, CONCAT_WS(' ', first_name, second_name, last_name) AS full_name,
    similarity(CONCAT_WS(' ', first_name, second_name, last_name), $1) AS sim
FROM resident
WHERE deleted_at IS NULL AND
    similarity(CONCAT_WS(' ', first_name, second_name, last_name), $1) > 0.2
ORDER BY sim DESC, created_at ASC
LIMIT $3 OFFSET $2
`

type SearchResidentsParams struct {
	Query  string `db:"query" json:"query"`
	Offset int32  `db:"offset" json:"offset"`
	Limit  int32  `db:"limit" json:"limit"`
}

type SearchResidentsRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	Email      string     `db:"email" json:"email"`
	FirstName  string     `db:"first_name" json:"first_name"`
	SecondName string     `db:"second_name" json:"second_name"`
	LastName   string     `db:"last_name" json:"last_name"`
	BirthDate  time.Time  `db:"birth_date" json:"birth_date"`
	Gender     string     `db:"gender" json:"gender"`
	Phone      string     `db:"phone" json:"phone"`
	AddressID  *uuid.UUID `db:"address_id" json:"address_id"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
	FullName   string     `db:"full_name" json:"full_name"`
	Sim        float32    `db:"sim" json:"sim"`
}

func (q *Queries) SearchResidents(ctx context.Context, arg SearchResidentsParams) ([]SearchResidentsRow, error) {
	rows, err := q.db.Query(ctx, searchResidents, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchResidentsRow{}
	for rows.Next() {
		var i SearchResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.Phone,
			&i.AddressID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResident = `-- name: UpdateResident :exec
UPDATE resident SET
  email = $2, first_name = $3, second_name = $4, last_name = $5,
  birth_date = $6, gender = $7, phone = $8
WHERE id = $1
`

type UpdateResidentParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Email      string    `db:"email" json:"email"`
	FirstName  string    `db:"first_name" json:"first_name"`
	SecondName string    `db:"second_name" json:"second_name"`
	LastName   string    `db:"last_name" json:"last_name"`
	BirthDate  time.Time `db:"birth_date" json:"birth_date"`
	Gender     string    `db:"gender" json:"gender"`
	Phone      string    `db:"phone" json:"phone"`
}

func (q *Queries) UpdateResident(ctx context.Context, arg UpdateResidentParams) error {
	_, err := q.db.Exec(ctx, updateResident,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
	)
	return err
}

const updateResidentAddress = `-- name: UpdateResidentAddress :exec
UPDATE resident SET address_id = $1 WHERE id = $2
`

type UpdateResidentAddressParams struct {
	AddressID *uuid.UUID `db:"address_id" json:"address_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateResidentAddress(ctx context.Context, arg UpdateResidentAddressParams) error {
	_, err := q.db.Exec(ctx, updateResidentAddress, arg.AddressID, arg.ID)
	return err
}
