// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: role.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAssignablePermissionsForActor = `-- name: GetAssignablePermissionsForActor :many
SELECT p.name, p.label, p.description
FROM permission p
WHERE EXISTS (
    SELECT 1
    FROM role_permission rp
    JOIN role role ON role.slug = rp.role_slug
    WHERE rp.permission_name = p.name
      AND role.level_rank = (
          SELECT level_rank FROM role WHERE slug = (SELECT role_slug FROM "user" WHERE id = $1)
      )
)
ORDER BY p.name
`

// returns every permission the actor can legally manipulate
func (q *Queries) GetAssignablePermissionsForActor(ctx context.Context, id uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAssignablePermissionsForActor, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Name, &i.Label, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentUserMaxRoleLevel = `-- name: GetCurrentUserMaxRoleLevel :one
SELECT r.level_rank
FROM "user" u
JOIN role r ON r.slug = u.role_slug
WHERE u.id = $1
`

func (q *Queries) GetCurrentUserMaxRoleLevel(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentUserMaxRoleLevel, id)
	var level_rank int32
	err := row.Scan(&level_rank)
	return level_rank, err
}

const getRoleTree = `-- name: GetRoleTree :many
WITH RECURSIVE tree AS (
    SELECT slug, name, parent_role_slug, level_rank
    FROM role
    WHERE role.slug = $1
    UNION
    SELECT r.slug, r.name, r.parent_role_slug, r.level_rank
    FROM role r
    JOIN tree t ON r.parent_role_slug = t.slug
)
SELECT slug, name, parent_role_slug, level_rank FROM tree ORDER BY level_rank
`

type GetRoleTreeRow struct {
	Slug           string  `db:"slug" json:"slug"`
	Name           string  `db:"name" json:"name"`
	ParentRoleSlug *string `db:"parent_role_slug" json:"parent_role_slug"`
	LevelRank      int32   `db:"level_rank" json:"level_rank"`
}

func (q *Queries) GetRoleTree(ctx context.Context, slug string) ([]GetRoleTreeRow, error) {
	rows, err := q.db.Query(ctx, getRoleTree, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoleTreeRow{}
	for rows.Next() {
		var i GetRoleTreeRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.ParentRoleSlug,
			&i.LevelRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionMatrixInScope = `-- name: ListPermissionMatrixInScope :many
WITH scope_users AS (
    SELECT u.id, u.email, r.slug AS role_slug, r.name AS role_name
    FROM "user" u
    JOIN role r ON r.slug = u.role_slug
    WHERE
    ($1::uuid IS NULL OR u.city_id = $1::uuid) AND
    ($2::uuid IS NULL OR u.subcity_id = $2::uuid) AND
    ($3::uuid IS NULL OR u.kebele_id = $3::uuid)
)
SELECT
    su.id             AS user_id,
    su.email,
    su.role_slug,
    su.role_name,
    p.name            AS permission_name,
    p.label,
    p.description,
    COALESCE(
        o.is_granted,
        EXISTS (
            SELECT 1
            FROM role_permission rp
            JOIN role child ON child.slug = rp.role_slug
            WHERE rp.permission_name = p.name
              AND child.level_rank >= (
                  SELECT level_rank FROM role WHERE slug = su.role_slug
              )
        )
    ) AS granted,
    o.is_granted IS NOT NULL AS overridden
FROM permission p
CROSS JOIN scope_users su
LEFT  JOIN user_permission_override o
       ON o.user_id = su.id AND o.permission_name = p.name
ORDER BY su.role_slug, su.id, p.name
`

type ListPermissionMatrixInScopeParams struct {
	CityID    uuid.UUID `db:"city_id" json:"city_id"`
	SubcityID uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID  uuid.UUID `db:"kebele_id" json:"kebele_id"`
}

type ListPermissionMatrixInScopeRow struct {
	UserID         uuid.UUID   `db:"user_id" json:"user_id"`
	Email          string      `db:"email" json:"email"`
	RoleSlug       string      `db:"role_slug" json:"role_slug"`
	RoleName       string      `db:"role_name" json:"role_name"`
	PermissionName string      `db:"permission_name" json:"permission_name"`
	Label          string      `db:"label" json:"label"`
	Description    *string     `db:"description" json:"description"`
	Granted        bool        `db:"granted" json:"granted"`
	Overridden     interface{} `db:"overridden" json:"overridden"`
}

func (q *Queries) ListPermissionMatrixInScope(ctx context.Context, arg ListPermissionMatrixInScopeParams) ([]ListPermissionMatrixInScopeRow, error) {
	rows, err := q.db.Query(ctx, listPermissionMatrixInScope, arg.CityID, arg.SubcityID, arg.KebeleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionMatrixInScopeRow{}
	for rows.Next() {
		var i ListPermissionMatrixInScopeRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.RoleSlug,
			&i.RoleName,
			&i.PermissionName,
			&i.Label,
			&i.Description,
			&i.Granted,
			&i.Overridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT
    r.slug          AS role_slug,
    r.name          AS role_name,
    r.level_rank    AS role_level_rank,
    p.name          AS permission_name,
    p.label         AS permission_label,
    p.description   AS permission_description,
    CASE
        WHEN rp.permission_name IS NOT NULL THEN true
        ELSE false
    END             AS assigned
FROM role r
CROSS JOIN permission p                   -- every permission
LEFT JOIN role_permission rp
       ON rp.role_slug = r.slug
      AND rp.permission_name = p.name
ORDER BY r.level_rank, p.name
`

type ListRolePermissionsRow struct {
	RoleSlug              string  `db:"role_slug" json:"role_slug"`
	RoleName              string  `db:"role_name" json:"role_name"`
	RoleLevelRank         int32   `db:"role_level_rank" json:"role_level_rank"`
	PermissionName        string  `db:"permission_name" json:"permission_name"`
	PermissionLabel       string  `db:"permission_label" json:"permission_label"`
	PermissionDescription *string `db:"permission_description" json:"permission_description"`
	Assigned              bool    `db:"assigned" json:"assigned"`
}

func (q *Queries) ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionsRow{}
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(
			&i.RoleSlug,
			&i.RoleName,
			&i.RoleLevelRank,
			&i.PermissionName,
			&i.PermissionLabel,
			&i.PermissionDescription,
			&i.Assigned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT slug, name, parent_role_slug, level_rank FROM role ORDER BY level_rank
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.ParentRoleSlug,
			&i.LevelRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
