// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: setting.sql

package repository

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT id, idcard_expiration_duration, created_at, updated_at
FROM setting
WHERE id = $1
`

func (q *Queries) GetSetting(ctx context.Context, id string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, id)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.IdcardExpirationDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE setting
SET idcard_expiration_duration = $1
WHERE id = $1
`

func (q *Queries) UpdateSetting(ctx context.Context, idcardExpirationDuration int32) error {
	_, err := q.db.Exec(ctx, updateSetting, idcardExpirationDuration)
	return err
}
