// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subcity.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListSubcities = `-- name: CountListSubcities :one
SELECT COUNT(*)
FROM subcity
WHERE deleted_at IS NULL
`

func (q *Queries) CountListSubcities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListSubcities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchSubCities = `-- name: CountSearchSubCities :one
SELECT COUNT(*)
FROM subcity
WHERE deleted_at IS NULL AND
    similarity(CONCAT_WS(' ', name), $1) > 0.2
`

func (q *Queries) CountSearchSubCities(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSubCities, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubCity = `-- name: CreateSubCity :one
INSERT INTO subcity (name, lat, lon, city_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, lat, lon, city_id, created_at, deleted_at
`

type CreateSubCityParams struct {
	Name   string    `db:"name" json:"name"`
	Lat    *float64  `db:"lat" json:"lat"`
	Lon    *float64  `db:"lon" json:"lon"`
	CityID uuid.UUID `db:"city_id" json:"city_id"`
}

func (q *Queries) CreateSubCity(ctx context.Context, arg CreateSubCityParams) (Subcity, error) {
	row := q.db.QueryRow(ctx, createSubCity,
		arg.Name,
		arg.Lat,
		arg.Lon,
		arg.CityID,
	)
	var i Subcity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getKebelesForSubCity = `-- name: GetKebelesForSubCity :many
SELECT k.id, k.name, k.lat, k.lon, k.subcity_id, k.city_id, k.created_at, k.deleted_at, u.id as executive_id,
    CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS executive_name
FROM kebele k
JOIN subcity sc ON sc.id = k.subcity_id
LEFT JOIN "user" u ON u.kebele_id = k.id AND u.role_slug = 'executive'
WHERE sc.id = $1 AND k.deleted_at IS NULL
`

type GetKebelesForSubCityRow struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	Name          string     `db:"name" json:"name"`
	Lat           *float64   `db:"lat" json:"lat"`
	Lon           *float64   `db:"lon" json:"lon"`
	SubcityID     uuid.UUID  `db:"subcity_id" json:"subcity_id"`
	CityID        uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	DeletedAt     *time.Time `db:"deleted_at" json:"deleted_at"`
	ExecutiveID   *uuid.UUID `db:"executive_id" json:"executive_id"`
	ExecutiveName string     `db:"executive_name" json:"executive_name"`
}

func (q *Queries) GetKebelesForSubCity(ctx context.Context, id uuid.UUID) ([]GetKebelesForSubCityRow, error) {
	rows, err := q.db.Query(ctx, getKebelesForSubCity, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetKebelesForSubCityRow{}
	for rows.Next() {
		var i GetKebelesForSubCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.SubcityID,
			&i.CityID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ExecutiveID,
			&i.ExecutiveName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCity = `-- name: GetSubCity :one
SELECT s.id, s.name, s.lat, s.lon, s.city_id, s.created_at, s.deleted_at, c.name as city_name, u.id as manager_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS manager_name
FROM subcity s
LEFT JOIN city c ON c.id = s.city_id
LEFT JOIN "user" u ON u.subcity_id = s.id AND u.role_slug = 'manager'
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetSubCityRow struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	Lat         *float64   `db:"lat" json:"lat"`
	Lon         *float64   `db:"lon" json:"lon"`
	CityID      uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
	CityName    *string    `db:"city_name" json:"city_name"`
	ManagerID   *uuid.UUID `db:"manager_id" json:"manager_id"`
	ManagerName string     `db:"manager_name" json:"manager_name"`
}

func (q *Queries) GetSubCity(ctx context.Context, id uuid.UUID) (GetSubCityRow, error) {
	row := q.db.QueryRow(ctx, getSubCity, id)
	var i GetSubCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.CityName,
		&i.ManagerID,
		&i.ManagerName,
	)
	return i, err
}

const listSubCities = `-- name: ListSubCities :many
SELECT s.id, s.name, s.lat, s.lon, s.city_id, s.created_at, s.deleted_at, c.name as city_name, u.id as manager_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS manager_name
FROM subcity s
LEFT JOIN city c ON c.id = s.city_id
LEFT JOIN "user" u ON u.subcity_id = s.id AND u.role_slug = 'manager'
WHERE s.deleted_at IS NULL
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubCitiesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListSubCitiesRow struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	Lat         *float64   `db:"lat" json:"lat"`
	Lon         *float64   `db:"lon" json:"lon"`
	CityID      uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
	CityName    *string    `db:"city_name" json:"city_name"`
	ManagerID   *uuid.UUID `db:"manager_id" json:"manager_id"`
	ManagerName string     `db:"manager_name" json:"manager_name"`
}

func (q *Queries) ListSubCities(ctx context.Context, arg ListSubCitiesParams) ([]ListSubCitiesRow, error) {
	rows, err := q.db.Query(ctx, listSubCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubCitiesRow{}
	for rows.Next() {
		var i ListSubCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.CityID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.CityName,
			&i.ManagerID,
			&i.ManagerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubCities = `-- name: SearchSubCities :many
SELECT sb.id, sb.name, sb.lat, sb.lon, sb.city_id, sb.created_at, sb.deleted_at, c.id, c.name, c.lat, c.lon, c.created_at, c.deleted_at, u.id, first_name, second_name, last_name, email, phone, password_hash, u.city_id, subcity_id, kebele_id, role_slug, u.created_at, u.deleted_at, c.name as city_name, u.id as manager_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS manager_name,
    similarity(CONCAT_WS(' ', sb.name, c.name), $1) AS sim
FROM subcity sb
JOIN city c ON c.id = sb.city_id
LEFT JOIN "user" u ON u.subcity_id = sb.id AND u.role_slug = 'manager'
WHERE sb.deleted_at IS NULL AND
    similarity(CONCAT_WS(' ', sb.name, c.name), $1) > 0.2
ORDER BY sim DESC, sb.created_at DESC
LIMIT $3 OFFSET $2
`

type SearchSubCitiesParams struct {
	Query  string `db:"query" json:"query"`
	Offset int32  `db:"offset" json:"offset"`
	Limit  int32  `db:"limit" json:"limit"`
}

type SearchSubCitiesRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Lat          *float64   `db:"lat" json:"lat"`
	Lon          *float64   `db:"lon" json:"lon"`
	CityID       uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
	ID_2         uuid.UUID  `db:"id_2" json:"id_2"`
	Name_2       string     `db:"name_2" json:"name_2"`
	Lat_2        *float64   `db:"lat_2" json:"lat_2"`
	Lon_2        *float64   `db:"lon_2" json:"lon_2"`
	CreatedAt_2  time.Time  `db:"created_at_2" json:"created_at_2"`
	DeletedAt_2  *time.Time `db:"deleted_at_2" json:"deleted_at_2"`
	ID_3         *uuid.UUID `db:"id_3" json:"id_3"`
	FirstName    *string    `db:"first_name" json:"first_name"`
	SecondName   *string    `db:"second_name" json:"second_name"`
	LastName     *string    `db:"last_name" json:"last_name"`
	Email        *string    `db:"email" json:"email"`
	Phone        *string    `db:"phone" json:"phone"`
	PasswordHash *string    `db:"password_hash" json:"password_hash"`
	CityID_2     *uuid.UUID `db:"city_id_2" json:"city_id_2"`
	SubcityID    *uuid.UUID `db:"subcity_id" json:"subcity_id"`
	KebeleID     *uuid.UUID `db:"kebele_id" json:"kebele_id"`
	RoleSlug     *string    `db:"role_slug" json:"role_slug"`
	CreatedAt_3  *time.Time `db:"created_at_3" json:"created_at_3"`
	DeletedAt_3  *time.Time `db:"deleted_at_3" json:"deleted_at_3"`
	CityName     string     `db:"city_name" json:"city_name"`
	ManagerID    *uuid.UUID `db:"manager_id" json:"manager_id"`
	ManagerName  string     `db:"manager_name" json:"manager_name"`
	Sim          float32    `db:"sim" json:"sim"`
}

func (q *Queries) SearchSubCities(ctx context.Context, arg SearchSubCitiesParams) ([]SearchSubCitiesRow, error) {
	rows, err := q.db.Query(ctx, searchSubCities, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSubCitiesRow{}
	for rows.Next() {
		var i SearchSubCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.CityID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ID_2,
			&i.Name_2,
			&i.Lat_2,
			&i.Lon_2,
			&i.CreatedAt_2,
			&i.DeletedAt_2,
			&i.ID_3,
			&i.FirstName,
			&i.SecondName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.CityID_2,
			&i.SubcityID,
			&i.KebeleID,
			&i.RoleSlug,
			&i.CreatedAt_3,
			&i.DeletedAt_3,
			&i.CityName,
			&i.ManagerID,
			&i.ManagerName,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubCity = `-- name: UpdateSubCity :one
UPDATE subcity
SET name = $2, lat = $3, lon = $4
WHERE id = $1
RETURNING id, name, lat, lon, city_id, created_at, deleted_at
`

type UpdateSubCityParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Lat  *float64  `db:"lat" json:"lat"`
	Lon  *float64  `db:"lon" json:"lon"`
}

func (q *Queries) UpdateSubCity(ctx context.Context, arg UpdateSubCityParams) (Subcity, error) {
	row := q.db.QueryRow(ctx, updateSubCity,
		arg.ID,
		arg.Name,
		arg.Lat,
		arg.Lon,
	)
	var i Subcity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
