// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subcity.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListSubcities = `-- name: CountListSubcities :one
SELECT COUNT(*)
FROM subcity
WHERE deleted_at IS NULL
`

func (q *Queries) CountListSubcities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListSubcities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubCity = `-- name: CreateSubCity :one
INSERT INTO subcity (name, city_id)
VALUES ($1, $2)
RETURNING id, name, city_id, created_at, deleted_at
`

type CreateSubCityParams struct {
	Name   string    `db:"name" json:"name"`
	CityID uuid.UUID `db:"city_id" json:"city_id"`
}

func (q *Queries) CreateSubCity(ctx context.Context, arg CreateSubCityParams) (Subcity, error) {
	row := q.db.QueryRow(ctx, createSubCity, arg.Name, arg.CityID)
	var i Subcity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSubCity = `-- name: GetSubCity :one
SELECT s.id, s.name, s.city_id, s.created_at, s.deleted_at, c.name as city_name, u.id as manager_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS manager_name
FROM subcity s
LEFT JOIN city c ON c.id = s.city_id
LEFT JOIN "user" u ON u.subcity_id = s.id
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetSubCityRow struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	CityID      uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
	CityName    *string    `db:"city_name" json:"city_name"`
	ManagerID   *uuid.UUID `db:"manager_id" json:"manager_id"`
	ManagerName string     `db:"manager_name" json:"manager_name"`
}

func (q *Queries) GetSubCity(ctx context.Context, id uuid.UUID) (GetSubCityRow, error) {
	row := q.db.QueryRow(ctx, getSubCity, id)
	var i GetSubCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.CityName,
		&i.ManagerID,
		&i.ManagerName,
	)
	return i, err
}

const listSubCities = `-- name: ListSubCities :many
SELECT s.id, s.name, s.city_id, s.created_at, s.deleted_at, c.name as city_name, u.id as manager_id, CONCAT_WS(' ', u.first_name, u.second_name, u.last_name) AS manager_name
FROM subcity s
LEFT JOIN city c ON c.id = s.city_id
LEFT JOIN "user" u ON u.subcity_id = s.id
WHERE s.deleted_at IS NULL
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubCitiesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListSubCitiesRow struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	CityID      uuid.UUID  `db:"city_id" json:"city_id"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at"`
	CityName    *string    `db:"city_name" json:"city_name"`
	ManagerID   *uuid.UUID `db:"manager_id" json:"manager_id"`
	ManagerName string     `db:"manager_name" json:"manager_name"`
}

func (q *Queries) ListSubCities(ctx context.Context, arg ListSubCitiesParams) ([]ListSubCitiesRow, error) {
	rows, err := q.db.Query(ctx, listSubCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubCitiesRow{}
	for rows.Next() {
		var i ListSubCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CityID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.CityName,
			&i.ManagerID,
			&i.ManagerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
