// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name, second_name, last_name,
  email, phone, password, role
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type CreateUserParams struct {
	FirstName  string `db:"first_name" json:"first_name"`
	SecondName string `db:"second_name" json:"second_name"`
	LastName   string `db:"last_name" json:"last_name"`
	Email      string `db:"email" json:"email"`
	Phone      string `db:"phone" json:"phone"`
	Password   string `db:"password" json:"password"`
	Role       string `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Role,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, second_name, last_name, email, phone, password, role, created_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, second_name, last_name, email, phone, password, role, created_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}
