// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: address.sql

package sqlc

import (
	"context"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
  house_number, district, city_id
) VALUES ($1, $2, $3)
RETURNING id
`

type CreateAddressParams struct {
	HouseNumber string
	District    string
	CityID      int32
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAddress, arg.HouseNumber, arg.District, arg.CityID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getAddress = `-- name: GetAddress :one
SELECT id, house_number, district, city_id, created_at, deleted_at, search_vector FROM address
WHERE house_number = $1 AND district = $2 AND city_id = $3
LIMIT 1
`

type GetAddressParams struct {
	HouseNumber string
	District    string
	CityID      int32
}

func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddress, arg.HouseNumber, arg.District, arg.CityID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.HouseNumber,
		&i.District,
		&i.CityID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
