// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: biometric.sql

package sqlc

import (
	"context"
)

const createBiometric = `-- name: CreateBiometric :exec
INSERT INTO biometric (
  resident_id, fingerprint, blood_type, face
) VALUES ($1, $2, $3, $4)
`

type CreateBiometricParams struct {
	ResidentID  int32
	Fingerprint []byte
	BloodType   string
	Face        string
}

func (q *Queries) CreateBiometric(ctx context.Context, arg CreateBiometricParams) error {
	_, err := q.db.Exec(ctx, createBiometric,
		arg.ResidentID,
		arg.Fingerprint,
		arg.BloodType,
		arg.Face,
	)
	return err
}
