// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: document.sql

package sqlc

import (
	"context"
)

const createDocument = `-- name: CreateDocument :exec
INSERT INTO document (
  type, number, resident_id, url, status
) VALUES ($1, $2, $3, $4, $5)
`

type CreateDocumentParams struct {
	Type       DocumentType
	Number     string
	ResidentID int32
	Url        string
	Status     DocumentStatus
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.Type,
		arg.Number,
		arg.ResidentID,
		arg.Url,
		arg.Status,
	)
	return err
}
