// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emergency.sql

package sqlc

import (
	"context"
)

const createEmergency = `-- name: CreateEmergency :exec
INSERT INTO emergency (
  resident_id, name, relation, phone
) VALUES ($1, $2, $3, $4)
`

type CreateEmergencyParams struct {
	ResidentID int32
	Name       string
	Relation   string
	Phone      string
}

func (q *Queries) CreateEmergency(ctx context.Context, arg CreateEmergencyParams) error {
	_, err := q.db.Exec(ctx, createEmergency,
		arg.ResidentID,
		arg.Name,
		arg.Relation,
		arg.Phone,
	)
	return err
}
