// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: employment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployment = `-- name: CreateEmployment :exec
INSERT INTO employment (
  resident_id, status, occupation, employer_name, work_address
) VALUES ($1, $2, $3, $4, $5)
`

type CreateEmploymentParams struct {
	ResidentID   int32
	Status       string
	Occupation   pgtype.Text
	EmployerName pgtype.Text
	WorkAddress  pgtype.Text
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) error {
	_, err := q.db.Exec(ctx, createEmployment,
		arg.ResidentID,
		arg.Status,
		arg.Occupation,
		arg.EmployerName,
		arg.WorkAddress,
	)
	return err
}
