// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_resident.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getResidentFull = `-- name: GetResidentFull :one
SELECT
  r.id, r.email, r.first_name, r.second_name, r.last_name, r.birth_date, r.gender, r.phone, r.marital_status, r.religion, r.ethnicity, r.disability_status, r.education_level, r.languages_spoken, r.address_id, r.created_at, r.deleted_at, r.search_vector,
  a.house_number,
  a.district,
  c.name AS city_name,
  rg.name AS region_name,
  b.blood_type,
  b.face,
  d.type AS document_type,
  d.status AS document_status,
  d.url AS document_url,
  d.number AS document_number,
  e.status AS employment_status,
  e.occupation,
  e.employer_name,
  e.work_address,
  em.name AS emergency_contact_name,
  em.relation AS emergency_contact_relation,
  em.phone AS emergency_contact_phone
FROM resident r
LEFT JOIN address a ON r.address_id = a.id
LEFT JOIN city c ON a.city_id = c.id
LEFT JOIN region rg ON c.region_id = rg.id
LEFT JOIN biometric b ON r.id = b.resident_id
LEFT JOIN document d ON r.id = d.resident_id
LEFT JOIN employment e ON r.id = e.resident_id
LEFT JOIN emergency em ON r.id = em.resident_id
WHERE r.id = $1 AND r.deleted_at IS NULL
`

type GetResidentFullRow struct {
	ID                       int32
	Email                    string
	FirstName                string
	SecondName               string
	LastName                 string
	BirthDate                pgtype.Timestamp
	Gender                   Gender
	Phone                    string
	MaritalStatus            MaritalStatus
	Religion                 Religion
	Ethnicity                pgtype.Text
	DisabilityStatus         pgtype.Text
	EducationLevel           pgtype.Text
	LanguagesSpoken          string
	AddressID                int32
	CreatedAt                pgtype.Timestamp
	DeletedAt                pgtype.Timestamp
	SearchVector             interface{}
	HouseNumber              pgtype.Text
	District                 pgtype.Text
	CityName                 pgtype.Text
	RegionName               pgtype.Text
	BloodType                pgtype.Text
	Face                     pgtype.Text
	DocumentType             NullDocumentType
	DocumentStatus           NullDocumentStatus
	DocumentUrl              pgtype.Text
	DocumentNumber           pgtype.Text
	EmploymentStatus         pgtype.Text
	Occupation               pgtype.Text
	EmployerName             pgtype.Text
	WorkAddress              pgtype.Text
	EmergencyContactName     pgtype.Text
	EmergencyContactRelation pgtype.Text
	EmergencyContactPhone    pgtype.Text
}

func (q *Queries) GetResidentFull(ctx context.Context, id int32) (GetResidentFullRow, error) {
	row := q.db.QueryRow(ctx, getResidentFull, id)
	var i GetResidentFullRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.SecondName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.Phone,
		&i.MaritalStatus,
		&i.Religion,
		&i.Ethnicity,
		&i.DisabilityStatus,
		&i.EducationLevel,
		&i.LanguagesSpoken,
		&i.AddressID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.HouseNumber,
		&i.District,
		&i.CityName,
		&i.RegionName,
		&i.BloodType,
		&i.Face,
		&i.DocumentType,
		&i.DocumentStatus,
		&i.DocumentUrl,
		&i.DocumentNumber,
		&i.EmploymentStatus,
		&i.Occupation,
		&i.EmployerName,
		&i.WorkAddress,
		&i.EmergencyContactName,
		&i.EmergencyContactRelation,
		&i.EmergencyContactPhone,
	)
	return i, err
}
