// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DocumentStatus string

const (
	DocumentStatusPENDING  DocumentStatus = "PENDING"
	DocumentStatusAPPROVED DocumentStatus = "APPROVED"
	DocumentStatusREJECTED DocumentStatus = "REJECTED"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus
	Valid          bool // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type DocumentType string

const (
	DocumentTypeID             DocumentType = "ID"
	DocumentTypePASSPORT       DocumentType = "PASSPORT"
	DocumentTypeDRIVINGLICENSE DocumentType = "DRIVING_LICENSE"
	DocumentTypeNATIONALID     DocumentType = "NATIONAL_ID"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType
	Valid        bool // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type Gender string

const (
	GenderMALE   Gender = "MALE"
	GenderFEMALE Gender = "FEMALE"
	GenderOTHER  Gender = "OTHER"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type MaritalStatus string

const (
	MaritalStatusSINGLE   MaritalStatus = "SINGLE"
	MaritalStatusMARRIED  MaritalStatus = "MARRIED"
	MaritalStatusDIVORCED MaritalStatus = "DIVORCED"
	MaritalStatusWIDOWED  MaritalStatus = "WIDOWED"
)

func (e *MaritalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaritalStatus(s)
	case string:
		*e = MaritalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaritalStatus: %T", src)
	}
	return nil
}

type NullMaritalStatus struct {
	MaritalStatus MaritalStatus
	Valid         bool // Valid is true if MaritalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaritalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaritalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaritalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaritalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaritalStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCASH         PaymentMethod = "CASH"
	PaymentMethodMOBILEMONEY  PaymentMethod = "MOBILE_MONEY"
	PaymentMethodBANKTRANSFER PaymentMethod = "BANK_TRANSFER"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDING  PaymentStatus = "PENDING"
	PaymentStatusAPPROVED PaymentStatus = "APPROVED"
	PaymentStatusREJECTED PaymentStatus = "REJECTED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Religion string

const (
	ReligionCHRISTIAN Religion = "CHRISTIAN"
	ReligionMUSLIM    Religion = "MUSLIM"
	ReligionHINDU     Religion = "HINDU"
	ReligionBUDDHIST  Religion = "BUDDHIST"
	ReligionOTHER     Religion = "OTHER"
	ReligionNONE      Religion = "NONE"
)

func (e *Religion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Religion(s)
	case string:
		*e = Religion(s)
	default:
		return fmt.Errorf("unsupported scan type for Religion: %T", src)
	}
	return nil
}

type NullReligion struct {
	Religion Religion
	Valid    bool // Valid is true if Religion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReligion) Scan(value interface{}) error {
	if value == nil {
		ns.Religion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Religion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReligion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Religion), nil
}

type Address struct {
	ID           int32
	HouseNumber  string
	District     string
	CityID       int32
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Biometric struct {
	ID           int32
	ResidentID   int32
	Fingerprint  []byte
	BloodType    string
	Face         string
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type City struct {
	ID           int32
	Name         string
	RegionID     int32
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Document struct {
	ID           int32
	Type         DocumentType
	ResidentID   int32
	Url          string
	Status       DocumentStatus
	Number       string
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Emergency struct {
	ID           int32
	ResidentID   int32
	Name         string
	Relation     string
	Phone        string
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Employment struct {
	ID           int32
	ResidentID   int32
	Status       string
	Occupation   pgtype.Text
	EmployerName pgtype.Text
	WorkAddress  pgtype.Text
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Idcard struct {
	ID           int32
	ResidentID   int32
	Number       string
	IssueDate    pgtype.Timestamp
	ExpiryDate   pgtype.Timestamp
	IssuePlace   string
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Payment struct {
	ID           int32
	ResidentID   int32
	Amount       float64
	Description  string
	Status       PaymentStatus
	Reference    string
	Method       PaymentMethod
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type RefreshToken struct {
	ID        int32
	UserID    pgtype.Int4
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type Region struct {
	ID           int32
	Name         string
	CreatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	SearchVector interface{}
}

type Resident struct {
	ID               int32
	Email            string
	FirstName        string
	SecondName       string
	LastName         string
	BirthDate        pgtype.Timestamp
	Gender           Gender
	Phone            string
	MaritalStatus    MaritalStatus
	Religion         Religion
	Ethnicity        pgtype.Text
	DisabilityStatus pgtype.Text
	EducationLevel   pgtype.Text
	LanguagesSpoken  string
	AddressID        int32
	CreatedAt        pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
	SearchVector     interface{}
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID         int32
	FirstName  string
	SecondName string
	LastName   string
	Email      string
	Phone      string
	Password   string
	Role       string
	CreatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}
