// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resident.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResident = `-- name: CreateResident :one
INSERT INTO resident (
  email, first_name, second_name, last_name, birth_date, gender, phone,
  marital_status, religion, ethnicity, disability_status, education_level,
  languages_spoken
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13
)
RETURNING id
`

type CreateResidentParams struct {
	Email            string
	FirstName        string
	SecondName       string
	LastName         string
	BirthDate        pgtype.Timestamp
	Gender           Gender
	Phone            string
	MaritalStatus    MaritalStatus
	Religion         Religion
	Ethnicity        pgtype.Text
	DisabilityStatus pgtype.Text
	EducationLevel   pgtype.Text
	LanguagesSpoken  string
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) (int32, error) {
	row := q.db.QueryRow(ctx, createResident,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Phone,
		arg.MaritalStatus,
		arg.Religion,
		arg.Ethnicity,
		arg.DisabilityStatus,
		arg.EducationLevel,
		arg.LanguagesSpoken,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateResidentAddress = `-- name: UpdateResidentAddress :exec
UPDATE resident SET address_id = $1 WHERE id = $2
`

type UpdateResidentAddressParams struct {
	AddressID int32
	ID        int32
}

func (q *Queries) UpdateResidentAddress(ctx context.Context, arg UpdateResidentAddressParams) error {
	_, err := q.db.Exec(ctx, updateResidentAddress, arg.AddressID, arg.ID)
	return err
}
